const { getStore, connectLambda } = require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes',RP='ops-budget-record/',FP='ops-budget-file/',CP='ops-budget-counter/',IP='ops-intervention-record/';
const MAX_BODY=4.8*1024*1024,MAX_FILE=3.2*1024*1024;
const CATEGORIES=new Set(['Manutenção','Equipamento','Mobiliário','Obras','IT','Segurança','A&B','Housekeeping','Outra']);
const URGENCY=new Set(['Normal','Prioritário','Urgente']);
const STATES=new Set(['Rascunho','A aguardar propostas','Submetido à DO','A aguardar esclarecimentos','Aprovado','Recusado','Adjudicado','Intervenção criada','Concluído','Arquivado']);
const DECISIONS=new Set(['Aprovar','Recusar','Solicitar esclarecimentos']);
const HEAD={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const resp=(c,b)=>({statusCode:c,headers:HEAD,body:JSON.stringify(b)}),ok=b=>resp(200,b),bad=m=>resp(400,{error:m}),forbid=m=>resp(403,{error:m}),unauth=()=>resp(401,{error:'Sessão inválida ou expirada.'}),nf=()=>resp(404,{error:'Orçamento não encontrado.'});
const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n),norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/^(HOTEL\s+)?VILA\s+GALE\s+/,'').replace(/^VG(C)?\s+/,'').replace(/^COLLECTION\s+/,'').replace(/\s+/g,' ').trim(),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_');
const money=v=>{const n=Number(String(v??'').replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?Math.round(n*100)/100:null};
const role=u=>String(u?.role||'diretor').toLowerCase().replace('admin','direcao').replace('director','diretor'),direction=u=>role(u)==='direcao';
function hotels(u){if(direction(u))return['*'];const a=Array.isArray(u?.hotels)?u.hotels:(u?.hotel&&u.hotel!=='*'?[u.hotel]:[]);return[...new Set(a.map(x=>clean(x,120)).filter(Boolean))]}
const canHotel=(u,h)=>direction(u)||hotels(u).some(x=>norm(x)===norm(h)),canModule=u=>direction(u)||(Array.isArray(u?.modules)&&u.modules.includes('budgets'));
function from64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function verify(store,t){try{const p=String(t||'').split('.');if(p.length!==2)return null;const sec=(await store.get('_auth-secret-v1',{type:'json'}))?.value;if(!sec)return null;const exp=crypto.createHmac('sha256',Buffer.from(sec,'base64')).update(p[0]).digest(),act=from64(p[1]);if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const x=JSON.parse(from64(p[0]).toString('utf8'));if(!x.sub||x.exp<=Math.floor(Date.now()/1000))return null;const us=(await store.get('users',{type:'json'}))||{},u=us[x.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(x.av||1))return null;return u}catch(e){return null}}
const bearer=e=>{const h=e.headers?.authorization||e.headers?.Authorization||'',m=String(h).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
const key=id=>RP+safe(id),fileKey=(id,f)=>FP+safe(id)+'/'+safe(f),intKey=id=>IP+safe(id),audit=(u,a,d='')=>({at:new Date().toISOString(),user:u.user,name:u.name||u.user,profile:role(u),action:a,detail:clean(d,1600)});
async function get(store,id){return await store.get(key(id),{type:'json'})||null}async function save(store,r){r.updatedAt=new Date().toISOString();await store.setJSON(key(r.id),r);return r}
function prefix(h){const n=norm(h),m={'ESTORIL':'EST','CASCAIS':'CAS','OPERA':'OPE','ERICEIRA':'ERI','ALBACORA':'ALB','COIMBRA':'COI','AMPALIUS':'AMP'};return m[n]||(n.split(' ').map(x=>x[0]).join('').slice(0,3)||'HOT')}
async function code(store,h){const k=CP+safe(norm(h)),r=(await store.get(k,{type:'json'}))||{value:0},v=(Number(r.value)||0)+1;await store.setJSON(k,{value:v,updatedAt:new Date().toISOString()});return `ORC-${prefix(h)}-${new Date().getFullYear()}-${String(v).padStart(5,'0')}`}
const publicR=r=>({...r,quotes:(r.quotes||[]).map(q=>({...q,file:q.file?{id:q.file.id,name:q.file.name,type:q.file.type,size:q.file.size,createdAt:q.file.createdAt}:null}))});
async function list(store,u){const l=await store.list({prefix:RP}),out=[];for(const b of l.blobs||[]){const r=await store.get(b.key,{type:'json'});if(r&&canHotel(u,r.hotel))out.push(publicR(r))}return out.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
function quoteComplete(q){return q&&clean(q.supplier,200)&&Number.isFinite(Number(q.value))&&q.file?.id}
function activeQuotes(r){return (r.quotes||[]).filter(q=>!q.deleted)}
function proposalsEditable(r){return ['Rascunho','A aguardar propostas','A aguardar esclarecimentos'].includes(r.status)}
function body(event){if(Buffer.byteLength(event.body||'','utf8')>MAX_BODY)throw Object.assign(new Error('Pedido demasiado grande.'),{status:413});try{return JSON.parse(event.body||'{}')}catch(e){throw Object.assign(new Error('JSON inválido.'),{status:400})}}
exports.handler=async event=>{connectLambda(event);if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:HEAD,body:''};const store=getStore(STORE);try{const u=await verify(store,bearer(event));if(!u)return unauth();if(!canModule(u))return forbid('O seu perfil não tem acesso ao módulo de Orçamentos.');const q=event.queryStringParameters||{},action=clean(q.action||'list',60);
if(event.httpMethod==='GET'&&action==='list'){const data=await list(store,u);return ok({data,total:data.length})}
if(event.httpMethod==='GET'&&action==='file'){const r=await get(store,clean(q.id,160));if(!r||!canHotel(u,r.hotel))return nf();const qt=activeQuotes(r).find(x=>x.id===clean(q.quote,140));if(!qt?.file)return nf();const d=await store.get(fileKey(r.id,qt.file.id),{type:'json'});return d?.base64?ok({data:{name:qt.file.name,type:qt.file.type,base64:d.base64}}):nf()}
if(event.httpMethod!=='POST')return resp(405,{error:'Método não permitido.'});const p=body(event);
if(action==='create'){const hotel=clean(p.hotel,120),subject=clean(p.subject,300),description=clean(p.description,7000),category=clean(p.category,100),urgency=clean(p.urgency,50);if(!hotel||!subject||!description||!CATEGORIES.has(category)||!URGENCY.has(urgency))return bad('Preencha hotel, assunto, descrição, categoria e urgência.');if(!canHotel(u,hotel))return forbid('Só pode criar processos nos hotéis atribuídos ao seu utilizador.');const now=new Date().toISOString(),id=await code(store,hotel),r={id,code:id,hotel,year:new Date().getFullYear(),createdAt:now,updatedAt:now,subject,description,category,categoryOther:category==='Outra'?clean(p.categoryOther,300):'',urgency,location:clean(p.location,300),department:clean(p.department,180),owner:clean(p.owner,200),estimatedInvestment:money(p.estimatedInvestment),status:'Rascunho',quotes:[],selectedQuoteId:null,approval:null,adjudicatedAt:null,interventionId:null,finalCost:null,closed:false,archived:false,createdBy:{user:u.user,name:u.name||u.user,profile:role(u)},history:[audit(u,'Criou processo de orçamento',`${category} · ${urgency}`)]};await save(store,r);return ok({data:publicR(r)})}
const id=clean(p.id||q.id,160),r=await get(store,id);if(!r)return nf();if(!canHotel(u,r.hotel))return forbid('Só pode consultar ou alterar orçamentos do seu hotel.');
if(action==='update'){if(r.archived)return bad('Um processo arquivado não pode ser alterado.');if(!['Rascunho','A aguardar propostas','A aguardar esclarecimentos'].includes(r.status))return bad('Os dados base deixam de ser editáveis depois da submissão à DO.');r.subject=clean(p.subject,300)||r.subject;r.description=clean(p.description,7000)||r.description;const cat=clean(p.category||r.category,100),urg=clean(p.urgency||r.urgency,50);if(!CATEGORIES.has(cat)||!URGENCY.has(urg))return bad('Categoria ou urgência inválida.');r.category=cat;r.categoryOther=cat==='Outra'?clean(p.categoryOther,300):'';r.urgency=urg;r.location=clean(p.location,300);r.department=clean(p.department,180);r.owner=clean(p.owner,200);r.estimatedInvestment=money(p.estimatedInvestment);r.history=(r.history||[]).concat([audit(u,'Atualizou dados do processo','')]);await save(store,r);return ok({data:publicR(r)})}
if(action==='add-quote'||action==='replace-quote'){if(!proposalsEditable(r))return bad('As propostas estão bloqueadas depois da submissão à DO.');const supplier=clean(p.supplier,220),value=money(p.value),leadTime=clean(p.leadTime,120),warranty=clean(p.warranty,180),notes=clean(p.notes,1200),name=clean(p.name,240),type=clean(p.type,120),base64=String(p.base64||'').replace(/^data:[^;]+;base64,/,''),buf=Buffer.from(base64,'base64');if(!supplier||value===null||!name||!buf.length)return bad('Cada proposta exige fornecedor, valor e PDF.');if(buf.length>MAX_FILE)return resp(413,{error:'Cada PDF pode ter no máximo 3,2 MB.'});if(type!=='application/pdf')return bad('O documento da proposta tem de ser PDF.');let old=null;if(action==='replace-quote'){old=activeQuotes(r).find(x=>x.id===clean(p.quoteId,140));if(!old)return bad('Proposta a substituir não encontrada.')}else if(activeQuotes(r).length>=4)return bad('O processo só pode ter 3 ou 4 propostas.');const fid='f_'+Date.now().toString(36)+'_'+crypto.randomBytes(4).toString('hex');await store.setJSON(fileKey(r.id,fid),{base64,type,name});const qt={id:'q_'+Date.now().toString(36)+'_'+crypto.randomBytes(3).toString('hex'),supplier,value,leadTime,warranty,notes,file:{id:fid,name,type,size:buf.length,createdAt:new Date().toISOString()},createdAt:new Date().toISOString(),createdBy:u.user};if(old){old.deleted=true;old.replacedBy=qt.id;old.deletedAt=new Date().toISOString();r.history=(r.history||[]).concat([audit(u,'Substituiu proposta',`${old.supplier} → ${supplier}`)])}else r.history=(r.history||[]).concat([audit(u,'Adicionou proposta',`${supplier} · ${value.toFixed(2)} €`)]);r.quotes=(r.quotes||[]).concat([qt]);if(r.status==='Rascunho')r.status='A aguardar propostas';await save(store,r);return ok({data:publicR(r)})}
if(action==='delete-quote'){if(!proposalsEditable(r))return bad('As propostas estão bloqueadas depois da submissão à DO.');const qt=activeQuotes(r).find(x=>x.id===clean(p.quoteId,140));if(!qt)return bad('Proposta não encontrada.');qt.deleted=true;qt.deletedAt=new Date().toISOString();r.history=(r.history||[]).concat([audit(u,'Removeu proposta',qt.supplier)]);await save(store,r);return ok({data:publicR(r)})}
if(action==='submit'){const qs=activeQuotes(r);if(qs.length<3||qs.length>4||qs.some(q=>!quoteComplete(q)))return bad('Para submeter à DO são obrigatórias 3 ou 4 propostas completas, cada uma com fornecedor, valor e PDF.');r.status='Submetido à DO';r.history=(r.history||[]).concat([audit(u,'Submeteu à decisão DO',clean(p.comment,1200))]);await save(store,r);return ok({data:publicR(r)})}
if(action==='decision'){if(!direction(u))return forbid('A decisão está reservada à Direção de Operações.');if(!['Submetido à DO','A aguardar esclarecimentos'].includes(r.status))return bad('Este processo não está disponível para decisão da DO.');const decision=clean(p.decision,80),comment=clean(p.comment,1500);if(!DECISIONS.has(decision)||!comment)return bad('Decisão e comentário são obrigatórios.');let selected=null;if(decision==='Aprovar'){selected=activeQuotes(r).find(x=>x.id===clean(p.quoteId,140));if(!selected||!quoteComplete(selected))return bad('Ao aprovar é obrigatório selecionar uma das propostas submetidas.');r.selectedQuoteId=selected.id;r.approvedSupplier=selected.supplier;r.approvedValue=Number(selected.value)}r.approval={decision,comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user,quoteId:selected?.id||null};r.status=decision==='Aprovar'?'Aprovado':decision==='Recusar'?'Recusado':'A aguardar esclarecimentos';r.history=(r.history||[]).concat([audit(u,`Decisão DO: ${decision}`,selected?`${selected.supplier} · ${selected.value.toFixed(2)} € · ${comment}`:comment)]);await save(store,r);return ok({data:publicR(r)})}
if(action==='adjudicate'){if(r.status!=='Aprovado')return bad('Só é possível adjudicar um orçamento aprovado pela DO.');const selected=activeQuotes(r).find(x=>x.id===r.selectedQuoteId);if(!selected)return bad('A proposta aprovada deixou de estar disponível.');r.status='Adjudicado';r.adjudicatedAt=new Date().toISOString();r.history=(r.history||[]).concat([audit(u,'Adjudicou proposta aprovada',`${selected.supplier} · ${selected.value.toFixed(2)} € · ${clean(p.comment,1200)}`)]);await save(store,r);return ok({data:publicR(r)})}
if(action==='create-intervention'){if(!['Aprovado','Adjudicado'].includes(r.status))return bad('A intervenção só pode nascer de um orçamento aprovado.');if(r.interventionId)return bad('Este orçamento já tem uma intervenção associada.');const selected=activeQuotes(r).find(x=>x.id===r.selectedQuoteId);if(!selected)return bad('Não existe proposta aprovada.');const iid='INT-'+r.code.replace(/^ORC-/,'');const it={id:iid,code:iid,budgetId:r.id,hotel:r.hotel,subject:r.subject,supplier:selected.supplier,approvedValue:Number(selected.value),finalCost:null,owner:clean(p.owner,200)||r.owner,plannedStart:clean(p.plannedStart,30),plannedEnd:clean(p.plannedEnd,30),actualStart:'',actualEnd:'',scope:clean(p.scope,7000)||r.description,status:'A aguardar início',progress:0,warrantyEnd:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),history:[audit(u,'Criou intervenção a partir de orçamento aprovado',r.code)]};await store.setJSON(intKey(iid),it);r.interventionId=iid;r.status='Intervenção criada';r.history=(r.history||[]).concat([audit(u,'Criou intervenção',iid)]);await save(store,r);return ok({data:publicR(r),intervention:it})}
if(action==='final-cost'){if(!r.interventionId)return bad('Este orçamento ainda não originou uma intervenção.');const c=money(p.finalCost);if(c===null)return bad('Indique o custo final.');r.finalCost=c;const approved=Number(r.approvedValue||0),delta=c-approved,pct=approved?delta/approved*100:0;r.history=(r.history||[]).concat([audit(u,'Registou custo final',`${c.toFixed(2)} € · desvio ${delta>=0?'+':''}${delta.toFixed(2)} € (${pct>=0?'+':''}${pct.toFixed(1)}%)`)]);const it=await store.get(intKey(r.interventionId),{type:'json'});if(it){it.finalCost=c;it.updatedAt=new Date().toISOString();await store.setJSON(intKey(it.id),it)}await save(store,r);return ok({data:publicR(r)})}
if(action==='complete'){if(!['Recusado','Intervenção criada','Adjudicado','Aprovado'].includes(r.status))return bad('O processo ainda não está em condição de ser concluído.');r.status='Concluído';r.closed=true;r.closedAt=new Date().toISOString();r.history=(r.history||[]).concat([audit(u,'Concluiu processo',clean(p.comment,1200))]);await save(store,r);return ok({data:publicR(r)})}
if(action==='archive'){if(!r.closed||r.status!=='Concluído')return bad('Só pode arquivar um processo concluído.');r.archived=true;r.status='Arquivado';r.archivedAt=new Date().toISOString();r.history=(r.history||[]).concat([audit(u,'Arquivou processo','')]);await save(store,r);return ok({data:publicR(r)})}
return bad('Ação desconhecida.')}catch(e){console.error('budgets:',e);if(e.status)return resp(e.status,{error:e.message});return resp(500,{error:'Erro interno no módulo de Orçamentos.'})}};