const {getStore,connectLambda}=require('@netlify/blobs');
const crypto=require('crypto');
let webpush=null;try{webpush=require('web-push')}catch(e){}
const STORE='vg-dashboard-operacoes';
const CHAT='ops-msg-chat/',MSG='ops-msg-message/',FILE='ops-msg-file/',PUSH='ops-msg-push/',NOTICE='ops-msg-notice-read/';
const MAX_FILE=5*1024*1024,DELETE_MS=120000;
const H={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store'};
const resp=(c,b)=>({statusCode:c,headers:H,body:JSON.stringify(b)}),ok=b=>resp(200,b),bad=m=>resp(400,{error:m}),forbid=m=>resp(403,{error:m}),unauth=()=>resp(401,{error:'Sessão inválida ou expirada.'}),nf=m=>resp(404,{error:m||'Não encontrado.'});
const clean=(v,n=3000)=>String(v==null?'':v).trim().slice(0,n),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_');
function from64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function verify(store,t){try{const p=String(t||'').split('.');if(p.length!==2)return null;const sec=(await store.get('_auth-secret-v1',{type:'json'}))?.value;if(!sec)return null;const exp=crypto.createHmac('sha256',Buffer.from(sec,'base64')).update(p[0]).digest(),act=from64(p[1]);if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const x=JSON.parse(from64(p[0]).toString('utf8'));if(!x.sub||x.exp<=Math.floor(Date.now()/1000))return null;const us=(await store.get('users',{type:'json'}))||{},u=us[x.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(x.av||1))return null;return u}catch(e){return null}}
const bearer=e=>{const m=String(e.headers?.authorization||e.headers?.Authorization||'').match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
async function listAll(store,prefix){let out=[],cursor;do{const q={prefix};if(cursor)q.cursor=cursor;const r=await store.list(q);out=out.concat(r.blobs||[]);cursor=r.nextCursor||r.cursor||null}while(cursor);return out}
const chatKey=id=>CHAT+safe(id),msgPrefix=id=>MSG+safe(id)+'/',msgKey=(id,mid)=>msgPrefix(id)+safe(mid),fileKey=(id,mid,fid)=>FILE+safe(id)+'/'+safe(mid)+'/'+safe(fid);
const now=()=>new Date().toISOString();
function member(chat,user){return (chat.members||[]).find(m=>m.user===user&&!m.leftAt)}
function publicUsers(users){return Object.values(users||{}).filter(u=>u&&u.active!==false&&u.user).map(u=>({user:u.user,name:u.name||u.user,role:u.role||'',hotel:u.hotel||'',hotels:Array.isArray(u.hotels)?u.hotels:[]})).sort((a,b)=>a.name.localeCompare(b.name,'pt'))}
async function getChat(store,id){return await store.get(chatKey(id),{type:'json'})||null}
async function saveChat(store,c){c.updatedAt=now();await store.setJSON(chatKey(c.id),c);return c}
async function getMessages(store,c,u){const m=member(c,u.user);if(!m)return null;const blobs=await listAll(store,msgPrefix(c.id)),out=[];for(const b of blobs){const x=await store.get(b.key,{type:'json'});if(x&&x.createdAt>=m.joinedAt)out.push(x)}out.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));return out.map(x=>({...x,attachments:(x.attachments||[]).map(a=>({id:a.id,name:a.name,type:a.type,size:a.size}))}))}
async function chatSummary(store,c,u){const m=member(c,u.user);if(!m)return null;let unread=0;const blobs=await listAll(store,msgPrefix(c.id));for(const b of blobs){const x=await store.get(b.key,{type:'json'});if(x&&x.createdAt>=m.joinedAt&&x.from!==u.user&&x.createdAt>(m.readAt||m.joinedAt))unread++}return{id:c.id,name:c.name,group:!!c.group,members:c.members.filter(x=>!x.leftAt).map(x=>({user:x.user,joinedAt:x.joinedAt})),createdAt:c.createdAt,updatedAt:c.updatedAt,lastMessage:c.lastMessage||null,unread}}
async function pushUser(store,user,payload){if(!webpush||!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY)return;try{webpush.setVapidDetails(process.env.VAPID_SUBJECT||'https://dashboardtestes.netlify.app/',process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY)}catch(e){return}const rows=await listAll(store,PUSH+safe(user)+'/');for(const b of rows){const sub=await store.get(b.key,{type:'json'});if(!sub)continue;try{await webpush.sendNotification(sub,JSON.stringify(payload))}catch(e){if([404,410].includes(e.statusCode)){try{await store.delete(b.key)}catch(_){}}}}}
async function notifyMembers(store,c,sender,msg){const users=(c.members||[]).filter(m=>!m.leftAt&&m.user!==sender.user).map(m=>m.user);await Promise.all(users.map(x=>pushUser(store,x,{kind:'message',title:`VG Dashboard · ${sender.name||sender.user}`,body:msg.deletedAt?'Mensagem eliminada':clean(msg.text,180)||'Novo anexo',chatId:c.id,url:'/#messages'})))}
function processRecipients(r,users){const out=new Set(),creator=r?.createdBy?.user;if(creator)out.add(creator);if(r?.responsibleUser)out.add(r.responsibleUser);if(r?.approval?.user)out.add(r.approval.user);const pending=String(r?.status||'').toLowerCase().includes('aguardar decisão');if(pending)Object.values(users||{}).forEach(u=>{if(u&&u.active!==false&&['direcao','admin'].includes(String(u.role||'').toLowerCase()))out.add(u.user)});return out}
function noticeFor(type,r){const labels={complaint:'Reclamação',refund:'Devolução',budget:'Orçamento'},views={complaint:'complaints',refund:'refunds',budget:'budgets'};return{id:`${type}:${r.id}:${r.status}:${r.updatedAt||r.createdAt}`,type,processId:r.id,code:r.code||r.id,hotel:r.hotel||'',status:r.status||'',title:`${labels[type]} · ${r.code||r.id}`,body:[r.hotel,r.status].filter(Boolean).join(' · '),view:views[type],createdAt:r.updatedAt||r.createdAt||now(),url:`/#${views[type]}`}}
async function syncProcessNotices(store,users){const defs=[['complaint','ops-complaint-record/'],['refund','ops-refund/'],['budget','ops-budget-record/']];for(const [type,prefix] of defs){const blobs=await listAll(store,prefix);for(const b of blobs){const r=await store.get(b.key,{type:'json'});if(!r)continue;const recipients=processRecipients(r,users),n=noticeFor(type,r);for(const user of recipients){const k=NOTICE+safe(user)+'/'+safe(n.id),exists=await store.get(k,{type:'json'});if(exists)continue;await store.setJSON(k,{...n,user,read:false});await pushUser(store,user,{kind:'process',title:'VG Dashboard · '+n.title,body:n.body,url:n.url,view:n.view,processId:n.processId})}}}}
async function storedNotices(store,u){const rows=await listAll(store,NOTICE+safe(u.user)+'/'),out=[];for(const b of rows){const n=await store.get(b.key,{type:'json'});if(n)out.push(n)}return out.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,100)}
exports.handler=async event=>{connectLambda(event);if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:H,body:''};const store=getStore(STORE);try{const u=await verify(store,bearer(event));if(!u)return unauth();const q=event.queryStringParameters||{},action=clean(q.action||'list',50),users=(await store.get('users',{type:'json'}))||{};
if(event.httpMethod==='GET'&&action==='config')return ok({data:{vapidPublicKey:process.env.VAPID_PUBLIC_KEY||'',pushReady:!!(webpush&&process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY)}});
if(event.httpMethod==='GET'&&action==='users')return ok({data:publicUsers(users)});
if(event.httpMethod==='GET'&&action==='list'){await syncProcessNotices(store,users);const blobs=await listAll(store,CHAT),rows=[];for(const b of blobs){const c=await store.get(b.key,{type:'json'});if(c&&member(c,u.user)){const s=await chatSummary(store,c,u);if(s)rows.push(s)}}rows.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));return ok({data:rows,notifications:await storedNotices(store,u)})}
if(event.httpMethod==='GET'&&action==='messages'){const c=await getChat(store,q.id);if(!c)return nf('Conversa não encontrada.');if(!member(c,u.user))return forbid('Não tem acesso a esta conversa.');return ok({data:await getMessages(store,c,u),chat:await chatSummary(store,c,u)})}
if(event.httpMethod==='GET'&&action==='file'){const c=await getChat(store,q.id);if(!c||!member(c,u.user))return forbid('Não tem acesso a este anexo.');const m=await store.get(msgKey(c.id,q.message),{type:'json'}),a=(m?.attachments||[]).find(x=>x.id===q.file);if(!a)return nf('Anexo não encontrado.');const d=await store.get(fileKey(c.id,m.id,a.id),{type:'json'});return d?.base64?ok({data:{...a,base64:d.base64}}):nf('Anexo não encontrado.')}
if(event.httpMethod!=='POST')return resp(405,{error:'Método não permitido.'});let p={};try{p=JSON.parse(event.body||'{}')}catch(e){return bad('JSON inválido.')}
if(action==='subscribe-push'){const sub=p.subscription;if(!sub?.endpoint)return bad('Subscrição push inválida.');const id=crypto.createHash('sha256').update(sub.endpoint).digest('hex').slice(0,24);await store.setJSON(PUSH+safe(u.user)+'/'+id,sub);return ok({saved:true})}
if(action==='notice-read'){if(!p.id)return bad('Notificação obrigatória.');const k=NOTICE+safe(u.user)+'/'+safe(p.id),n=(await store.get(k,{type:'json'}))||{id:p.id,user:u.user};n.read=true;n.readAt=now();await store.setJSON(k,n);return ok({saved:true})}
if(action==='create'){const members=[...new Set((Array.isArray(p.members)?p.members:[]).map(clean).filter(x=>x&&x!==u.user))];if(!members.length)return bad('Selecione pelo menos um destinatário.');for(const x of members)if(!users[x]||users[x].active===false)return bad('Utilizador inválido: '+x);const t=now(),id='chat_'+Date.now().toString(36)+'_'+crypto.randomBytes(4).toString('hex'),all=[u.user,...members];const c={id,name:clean(p.name,160)||(members.length>1?members.map(x=>users[x]?.name||x).join(', '):(users[members[0]]?.name||members[0])),group:members.length>1,createdAt:t,updatedAt:t,createdBy:u.user,members:all.map(x=>({user:x,joinedAt:t,addedBy:u.user,readAt:x===u.user?t:''})),lastMessage:null};await saveChat(store,c);if(clean(p.text,5000)){p.id=id;p.text=clean(p.text,5000);return await handleSend(store,u,p,c)}return ok({data:await chatSummary(store,c,u)})}
const c=await getChat(store,p.id||q.id);if(!c)return nf('Conversa não encontrada.');const me=member(c,u.user);if(!me)return forbid('Não tem acesso a esta conversa.');
if(action==='send')return await handleSend(store,u,p,c);
if(action==='read'){me.readAt=now();await saveChat(store,c);return ok({saved:true})}
if(action==='add-members'){if(!c.group)return bad('Só pode adicionar participantes a conversas de grupo.');const add=[...new Set((p.members||[]).map(clean).filter(Boolean))],t=now();for(const x of add){if(!users[x]||users[x].active===false)continue;const old=(c.members||[]).find(m=>m.user===x);if(old&&!old.leftAt)continue;c.members.push({user:x,joinedAt:t,addedBy:u.user,readAt:t})}await saveChat(store,c);return ok({data:await chatSummary(store,c,u)})}
if(action==='delete-message'){const m=await store.get(msgKey(c.id,p.message),{type:'json'});if(!m)return nf('Mensagem não encontrada.');if(m.from!==u.user)return forbid('Só o autor pode eliminar a mensagem.');if(Date.now()-Date.parse(m.createdAt)>DELETE_MS)return bad('A mensagem só pode ser eliminada nos primeiros 2 minutos.');m.deletedAt=now();m.text='';for(const a of m.attachments||[]){try{await store.delete(fileKey(c.id,m.id,a.id))}catch(e){}}m.attachments=[];await store.setJSON(msgKey(c.id,m.id),m);if(c.lastMessage?.id===m.id)c.lastMessage={id:m.id,from:m.from,at:m.createdAt,text:'Mensagem eliminada',deleted:true};await saveChat(store,c);return ok({data:m})}
return bad('Ação desconhecida.')}catch(e){console.error('communications-v38:',e);return resp(500,{error:e.message||'Erro interno no sistema de mensagens.'})}};
async function handleSend(store,u,p,c){const text=clean(p.text,5000),files=Array.isArray(p.files)?p.files.slice(0,3):[];if(!text&&!files.length)return bad('Escreva uma mensagem ou adicione um anexo.');let total=0,prepared=[];for(const f of files){const name=clean(f.name,220),type=clean(f.type,120),raw=String(f.base64||'').replace(/^data:[^;]+;base64,/,'');let buf;try{buf=Buffer.from(raw,'base64')}catch(e){return bad('Anexo inválido.')}if(!buf.length||buf.length>MAX_FILE)return resp(413,{error:'Cada anexo pode ter no máximo 5 MB.'});total+=buf.length;if(total>MAX_FILE)return resp(413,{error:'O total de anexos por mensagem pode ter no máximo 5 MB.'});prepared.push({name,type,buf,raw})}const id='m_'+Date.now().toString(36)+'_'+crypto.randomBytes(4).toString('hex'),t=now(),attachments=[];for(const f of prepared){const fid='f_'+crypto.randomBytes(4).toString('hex'),meta={id:fid,name:f.name,type:f.type,size:f.buf.length};await store.setJSON(fileKey(c.id,id,fid),{base64:f.raw});attachments.push(meta)}const m={id,chatId:c.id,from:u.user,fromName:u.name||u.user,createdAt:t,text,attachments,deletedAt:null};await store.setJSON(msgKey(c.id,id),m);const me=member(c,u.user);if(me)me.readAt=t;c.lastMessage={id,from:u.user,fromName:u.name||u.user,at:t,text:text||((attachments[0]?.name)||'Anexo')};await saveChat(store,c);await notifyMembers(store,c,u,m);return ok({data:m,chat:await chatSummary(store,c,u)})}
