const { getStore, connectLambda } = require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes',RP='ops-complaint-record/',FP='ops-complaint-file/',CP='ops-complaint-counter/';
const MAX_BODY=4.8*1024*1024,MAX_FILE=3.2*1024*1024;
const ORIGINS=new Set(['Receção','Livro de Reclamações físico','Livro de Reclamações online','Telefone','Email/Internet','Outro']);
const STATES=new Set(['Nova','Em análise','A aguardar esclarecimentos','A aguardar decisão DO','Aprovada','Recusada','Resposta enviada ao cliente','Concluída','Arquivada']);
const COMP=new Set(['Sem compensação','Devolução','Noites gratuitas','Desconto','Refeições','Outra']);
const DECISIONS=new Set(['Aprovar','Recusar','Solicitar esclarecimentos']);
const HEAD={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const resp=(c,b)=>({statusCode:c,headers:HEAD,body:JSON.stringify(b)}),ok=b=>resp(200,b),bad=m=>resp(400,{error:m}),forbid=m=>resp(403,{error:m}),unauth=()=>resp(401,{error:'Sessão inválida ou expirada.'}),nf=()=>resp(404,{error:'Reclamação não encontrada.'});
const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n),norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/^(HOTEL\s+)?VILA\s+GALE\s+/,'').replace(/^VG(C)?\s+/,'').replace(/^COLLECTION\s+/,'').replace(/\s+/g,' ').trim(),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_');
const role=u=>String(u?.role||'diretor').toLowerCase().replace('admin','direcao').replace('director','diretor'),direction=u=>role(u)==='direcao';
function hotels(u){if(direction(u))return['*'];const a=Array.isArray(u?.hotels)?u.hotels:(u?.hotel&&u.hotel!=='*'?[u.hotel]:[]);return[...new Set(a.map(x=>clean(x,120)).filter(Boolean))]}
const canHotel=(u,h)=>direction(u)||hotels(u).some(x=>norm(x)===norm(h)),canModule=u=>direction(u)||(Array.isArray(u?.modules)&&u.modules.includes('complaints'));
function from64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function verify(store,t){try{const p=String(t||'').split('.');if(p.length!==2)return null;const sec=(await store.get('_auth-secret-v1',{type:'json'}))?.value;if(!sec)return null;const exp=crypto.createHmac('sha256',Buffer.from(sec,'base64')).update(p[0]).digest(),act=from64(p[1]);if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const x=JSON.parse(from64(p[0]).toString('utf8'));if(!x.sub||x.exp<=Math.floor(Date.now()/1000))return null;const us=(await store.get('users',{type:'json'}))||{},u=us[x.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(x.av||1))return null;return u}catch(e){return null}}
const bearer=e=>{const h=e.headers?.authorization||e.headers?.Authorization||'',m=String(h).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
const key=id=>RP+safe(id),fileKey=(id,f)=>FP+safe(id)+'/'+safe(f),audit=(u,a,d='')=>({at:new Date().toISOString(),user:u.user,name:u.name||u.user,profile:role(u),action:a,detail:clean(d,1200)});
async function get(store,id){return await store.get(key(id),{type:'json'})||null}async function save(store,r){r.updatedAt=new Date().toISOString();await store.setJSON(key(r.id),r);return r}
function prefix(h){const n=norm(h),m={'ESTORIL':'EST','CASCAIS':'CAS','OPERA':'OPE','ERICEIRA':'ERI','ALBACORA':'ALB','COIMBRA':'COI','AMPALIUS':'AMP'};return m[n]||(n.split(' ').map(x=>x[0]).join('').slice(0,3)||'HOT')}
async function code(store,h){const k=CP+safe(norm(h)),r=(await store.get(k,{type:'json'}))||{value:0},v=(Number(r.value)||0)+1;await store.setJSON(k,{value:v,updatedAt:new Date().toISOString()});return `REC-${prefix(h)}-${String(v).padStart(6,'0')}`}
function publicR(r){return{...r,files:(r.files||[]).map(f=>({id:f.id,name:f.name,type:f.type,size:f.size,createdAt:f.createdAt}))}}
async function list(store,u){const l=await store.list({prefix:RP}),out=[];for(const b of l.blobs||[]){const r=await store.get(b.key,{type:'json'});if(r&&canHotel(u,r.hotel))out.push(publicR(r))}return out.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
function compNeedsApproval(c){return c&&c!=='Sem compensação'}
function hasResponseSent(r){if(r?.responseSentAt)return true;return Array.isArray(r?.history)&&r.history.some(h=>String(h?.action||'').toLowerCase().includes('resposta enviada ao cliente'))}
exports.handler=async event=>{connectLambda(event);if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:HEAD,body:''};const store=getStore(STORE);try{const u=await verify(store,bearer(event));if(!u)return unauth();if(!canModule(u))return forbid('O seu perfil não tem acesso ao módulo de Reclamações.');const q=event.queryStringParameters||{},action=clean(q.action||'list',50);
if(event.httpMethod==='GET'&&action==='list'){const data=await list(store,u);return ok({data,total:data.length})}
if(event.httpMethod==='GET'&&action==='file'){const r=await get(store,clean(q.id,140));if(!r||!canHotel(u,r.hotel))return nf();const f=(r.files||[]).find(x=>x.id===clean(q.file,140));if(!f)return nf();const d=await store.get(fileKey(r.id,f.id),{type:'json'});return d?.base64?ok({data:{name:f.name,type:f.type,base64:d.base64}}):nf()}
if(event.httpMethod!=='POST')return resp(405,{error:'Método não permitido.'});if(Buffer.byteLength(event.body||'','utf8')>MAX_BODY)return resp(413,{error:'Pedido demasiado grande.'});let p={};try{p=JSON.parse(event.body||'{}')}catch(e){return bad('JSON inválido.')}
if(action==='create'){const hotel=clean(p.hotel,120),origin=clean(p.origin,100),description=clean(p.description,7000),department=clean(p.department,160),responsible=clean(p.responsible,180);if(!hotel||!ORIGINS.has(origin)||!description||!department)return bad('Preencha hotel, origem, descrição e departamento.');if(!canHotel(u,hotel))return forbid('Só pode criar reclamações nos hotéis atribuídos ao seu utilizador.');const now=new Date().toISOString(),id=await code(store,hotel);const r={id,code:id,hotel,createdAt:now,updatedAt:now,year:new Date().getFullYear(),complaintDate:clean(p.complaintDate,30)||now.slice(0,10),origin,originOther:origin==='Outro'?clean(p.originOther,300):'',customerName:clean(p.customerName,200),customerEmail:clean(p.customerEmail,240),customerPhone:clean(p.customerPhone,80),reservation:clean(p.reservation,100),room:clean(p.room,50),description,department,responsible,internalAnalysis:'',correctiveAction:'',status:'Nova',compensation:'Sem compensação',compensationDetail:'',compensationValue:'',compensationQty:'',approval:null,responseSentAt:null,responseChannel:'',responseComment:'',concludedAt:null,archived:false,files:[],createdBy:{user:u.user,name:u.name||u.user,profile:role(u)},history:[audit(u,'Criou reclamação',origin)]};await save(store,r);return ok({data:publicR(r)})}
const id=clean(p.id||q.id,140),r=await get(store,id);if(!r)return nf();if(!canHotel(u,r.hotel))return forbid('Só pode consultar ou alterar reclamações do seu hotel.');
if(action==='update'){if(r.archived)return bad('Uma reclamação arquivada não pode ser alterada.');const next=clean(p.status||r.status,80);if(!STATES.has(next)||next==='Arquivada')return bad('Estado inválido.');const old=r.status,statusComment=clean(p.statusComment,1200);if(old!==next&&!statusComment)return bad('Comentário obrigatório ao alterar o estado.');const comp=clean(p.compensation||r.compensation,100);if(!COMP.has(comp))return bad('Compensação inválida.');if(comp==='Outra'&&!clean(p.compensationDetail,500))return bad('Descreva a compensação Outra.');if(compNeedsApproval(comp)&&['Aprovada','Resposta enviada ao cliente','Concluída'].includes(next)&&r.approval?.decision!=='Aprovar')return bad('A compensação exige aprovação da Direção de Operações antes de avançar.');r.internalAnalysis=clean(p.internalAnalysis,7000);r.correctiveAction=clean(p.correctiveAction,5000);r.responsible=clean(p.responsible,180);r.department=clean(p.department,160)||r.department;r.compensation=comp;r.compensationDetail=clean(p.compensationDetail,1000);r.compensationValue=clean(p.compensationValue,80);r.compensationQty=clean(p.compensationQty,80);r.status=next;r.history=(r.history||[]).concat([audit(u,old===next?'Atualizou reclamação':`Estado: ${old} → ${next}`,statusComment)]);await save(store,r);return ok({data:publicR(r)})}
if(action==='submit-approval'){if(!compNeedsApproval(r.compensation))return bad('Este processo não tem compensação que necessite de aprovação.');r.status='A aguardar decisão DO';r.history=(r.history||[]).concat([audit(u,'Submeteu à decisão DO',clean(p.comment,1200))]);await save(store,r);return ok({data:publicR(r)})}
if(action==='decision'){if(!direction(u))return forbid('A decisão está reservada à Direção de Operações.');const decision=clean(p.decision,80),comment=clean(p.comment,1200);if(!DECISIONS.has(decision)||!comment)return bad('Decisão e comentário são obrigatórios.');r.approval={decision,comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user};r.status=decision==='Aprovar'?'Aprovada':decision==='Recusar'?'Recusada':'A aguardar esclarecimentos';r.history=(r.history||[]).concat([audit(u,`Decisão DO: ${decision}`,comment)]);await save(store,r);return ok({data:publicR(r)})}
if(action==='response-sent'){const channel=clean(p.channel,100),comment=clean(p.comment,1500);if(!channel||!comment)return bad('Canal e comentário da resposta enviada são obrigatórios.');if(compNeedsApproval(r.compensation)&&r.approval?.decision!=='Aprovar')return bad('Não pode responder com compensação sem aprovação da Direção de Operações.');r.responseSentAt=new Date().toISOString();r.responseChannel=channel;r.responseComment=comment;r.status='Resposta enviada ao cliente';r.history=(r.history||[]).concat([audit(u,'Registou resposta enviada ao cliente',`${channel} · ${comment}`)]);await save(store,r);return ok({data:publicR(r)})}
if(action==='conclude'){if(!hasResponseSent(r))return bad('Só pode concluir depois de a resposta ao cliente estar registada como enviada.');r.status='Concluída';r.concludedAt=new Date().toISOString();r.history=(r.history||[]).concat([audit(u,'Concluiu reclamação',clean(p.comment,1200))]);await save(store,r);return ok({data:publicR(r)})}
if(action==='archive'){if(!hasResponseSent(r))return bad('Não é possível arquivar: ainda não existe registo de resposta enviada ao cliente.');if(r.status!=='Concluída')return bad(`Não é possível arquivar: o processo está em "${r.status}" e tem de estar em "Concluída".`);r.archived=true;r.status='Arquivada';r.archivedAt=new Date().toISOString();r.history=(r.history||[]).concat([audit(u,'Arquivou reclamação','')]);await save(store,r);return ok({data:publicR(r)})}
if(action==='upload'){const name=clean(p.name,220),type=clean(p.type,120),base64=String(p.base64||'').replace(/^data:[^;]+;base64,/,''),buf=Buffer.from(base64,'base64');if(!name||!buf.length)return bad('Ficheiro inválido.');if(buf.length>MAX_FILE)return resp(413,{error:'Cada ficheiro pode ter no máximo 3,2 MB.'});if(!(type==='application/pdf'||type.startsWith('image/')))return bad('São permitidos PDF e imagens.');const fid='f_'+Date.now().toString(36)+'_'+crypto.randomBytes(4).toString('hex');await store.setJSON(fileKey(r.id,fid),{base64,type,name});r.files=(r.files||[]).concat([{id:fid,name,type,size:buf.length,createdAt:new Date().toISOString()}]);r.history=(r.history||[]).concat([audit(u,'Adicionou anexo',name)]);await save(store,r);return ok({data:publicR(r)})}
return bad('Ação desconhecida.')}catch(e){console.error('complaints:',e);return resp(500,{error:'Erro interno no módulo de Reclamações.'})}};