const { getStore, connectLambda }=require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes',RP='ops-energy-invoice/',FP='ops-energy-file/';
const HEAD={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const resp=(c,b)=>({statusCode:c,headers:HEAD,body:JSON.stringify(b)}),ok=b=>resp(200,b),bad=m=>resp(400,{error:m}),forbid=m=>resp(403,{error:m}),unauth=()=>resp(401,{error:'Sessão inválida ou expirada.'}),nf=()=>resp(404,{error:'Fatura não encontrada.'});
const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n),norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/^(HOTEL\s+)?VILA\s+GALE\s+/,'').replace(/^VG(C)?\s+/,'').replace(/^COLLECTION\s+/,'').replace(/\s+/g,' ').trim(),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_');
const role=u=>String(u?.role||'diretor').toLowerCase().replace('admin','direcao').replace('director','diretor'),direction=u=>role(u)==='direcao';
function hotels(u){if(direction(u))return['*'];const a=Array.isArray(u?.hotels)?u.hotels:(u?.hotel&&u.hotel!=='*'?[u.hotel]:[]);return[...new Set(a.map(x=>clean(x,120)).filter(Boolean))]}
const canHotel=(u,h)=>direction(u)||hotels(u).some(x=>norm(x)===norm(h)),canModule=u=>direction(u)||(Array.isArray(u?.modules)&&u.modules.includes('energy'));
function from64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function verify(store,t){try{const p=String(t||'').split('.');if(p.length!==2)return null;const sec=(await store.get('_auth-secret-v1',{type:'json'}))?.value;if(!sec)return null;const exp=crypto.createHmac('sha256',Buffer.from(sec,'base64')).update(p[0]).digest(),act=from64(p[1]);if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const x=JSON.parse(from64(p[0]).toString('utf8'));if(!x.sub||x.exp<=Math.floor(Date.now()/1000))return null;const us=(await store.get('users',{type:'json'}))||{},u=us[x.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(x.av||1))return null;return u}catch(e){return null}}
const bearer=e=>{const h=e.headers?.authorization||e.headers?.Authorization||'',m=String(h).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
const key=id=>RP+safe(id),fileKey=id=>FP+safe(id),audit=(u,a,d='')=>({at:new Date().toISOString(),user:u.user,name:u.name||u.user,profile:role(u),action:a,detail:clean(d,1200)});
async function get(store,id){return await store.get(key(id),{type:'json'})||null}async function save(store,r){r.updatedAt=new Date().toISOString();await store.setJSON(key(r.id),r);return r}
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim().replace(/\s/g,'').replace(/€/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function publicR(r){const x={...r};delete x.fileBlob;return x}
async function list(store,u){const l=await store.list({prefix:RP}),out=[];for(const b of l.blobs||[]){const r=await store.get(b.key,{type:'json'});if(r&&canHotel(u,r.hotel))out.push(publicR(r))}return out.sort((a,b)=>String(b.invoiceDate||b.createdAt).localeCompare(String(a.invoiceDate||a.createdAt)))}
async function duplicate(store,u,p,exclude){const rows=await list(store,u),inv=norm(p.invoiceNo),sup=norm(p.supplier),hot=norm(p.hotel);return rows.find(r=>r.id!==exclude&&norm(r.hotel)===hot&&norm(r.supplier)===sup&&norm(r.invoiceNo)===inv)||null}
function makeId(){return 'ENE-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase()}
function build(p,u,old){const type=clean(p.type||old?.type,30).toLowerCase(),unit=clean(p.unit||old?.unit,20)||((type==='water')?'m³':'kWh');if(!['electricity','gas','water'].includes(type))throw new Error('Tipo de energia inválido.');const periodEnd=clean(p.periodEnd||old?.periodEnd,30),d=periodEnd?new Date(periodEnd):null;const year=Number(p.year||old?.year||(d&&!isNaN(d)?d.getFullYear():new Date().getFullYear())),month=Number(p.month||old?.month||(d&&!isNaN(d)?d.getMonth()+1:0));return {...(old||{}),hotel:clean(p.hotel||old?.hotel,120),type,supplier:clean(p.supplier||old?.supplier,180),invoiceNo:clean(p.invoiceNo||old?.invoiceNo,100),invoiceDate:clean(p.invoiceDate||old?.invoiceDate,30),dueDate:clean(p.dueDate||old?.dueDate,30),periodStart:clean(p.periodStart||old?.periodStart,30),periodEnd,year,month,consumption:num(p.consumption??old?.consumption),unit,total:num(p.total??old?.total),net:num(p.net??old?.net),taxes:num(p.taxes??old?.taxes),fixedCost:num(p.fixedCost??old?.fixedCost),co2:num(p.co2??old?.co2),meter:clean(p.meter||old?.meter,180),contractedPower:num(p.contractedPower??old?.contractedPower),notes:clean(p.notes||old?.notes,3000),source:clean(p.source||old?.source||'manual',40),updatedBy:{user:u.user,name:u.name||u.user,profile:role(u)}}}
exports.handler=async event=>{connectLambda(event);if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:HEAD,body:''};const store=getStore(STORE);try{const u=await verify(store,bearer(event));if(!u)return unauth();if(!canModule(u))return forbid('O seu perfil não tem acesso ao módulo de Energia.');const q=event.queryStringParameters||{},action=clean(q.action||'list',40);
if(event.httpMethod==='GET'&&action==='list'){const data=await list(store,u);return ok({data,total:data.length})}
if(event.httpMethod==='GET'&&action==='file'){const r=await get(store,clean(q.id,160));if(!r||!canHotel(u,r.hotel)||!r.file)return nf();const d=await store.get(fileKey(r.id),{type:'json'});return d?.base64?ok({data:{name:r.file.name,type:r.file.type,base64:d.base64}}):nf()}
if(event.httpMethod!=='POST')return resp(405,{error:'Método não permitido.'});let p={};try{p=JSON.parse(event.body||'{}')}catch(e){return bad('JSON inválido.')}
if(action==='create'){const r=build(p,u);if(!r.hotel||!r.supplier||!r.invoiceNo||!r.invoiceDate||!r.periodStart||!r.periodEnd||!r.month||!r.year)return bad('Preencha hotel, fornecedor, nº fatura, datas da fatura e período.');if(!canHotel(u,r.hotel))return forbid('Só pode registar faturas nos hotéis atribuídos.');const dup=await duplicate(store,u,r);if(dup)return resp(409,{error:`Fatura duplicada: ${dup.invoiceNo} já existe em ${dup.hotel}.`,duplicateId:dup.id});r.id=makeId();r.createdAt=new Date().toISOString();r.createdBy={user:u.user,name:u.name||u.user,profile:role(u)};r.file=null;r.history=[audit(u,'Criou fatura',`${r.type} · ${r.supplier} · ${r.invoiceNo}`)];await save(store,r);return ok({data:publicR(r)})}
if(action==='batch'){const items=Array.isArray(p.items)?p.items:[];if(!items.length)return bad('Sem faturas para importar.');if(items.length>1000)return bad('Máximo de 1000 faturas por importação.');let created=0,duplicates=0,errors=[];for(let i=0;i<items.length;i++){try{const r=build({...items[i],source:'excel'},u);if(!r.hotel||!r.supplier||!r.invoiceNo||!r.invoiceDate||!r.periodStart||!r.periodEnd||!r.month||!r.year||!canHotel(u,r.hotel)){errors.push({row:i+2,error:'Dados obrigatórios/hotel inválido'});continue}if(await duplicate(store,u,r)){duplicates++;continue}r.id=makeId();r.createdAt=new Date().toISOString();r.createdBy={user:u.user,name:u.name||u.user,profile:role(u)};r.file=null;r.history=[audit(u,'Importou fatura','Excel/CSV')];await save(store,r);created++}catch(e){errors.push({row:i+2,error:e.message})}}return ok({created,duplicates,errors:errors.slice(0,50)})}
const id=clean(p.id||q.id,160),r=await get(store,id);if(!r)return nf();if(!canHotel(u,r.hotel))return forbid('Sem acesso a esta fatura.');
if(action==='update'){const n=build(p,u,r);if(!canHotel(u,n.hotel))return forbid('Sem acesso ao hotel indicado.');const dup=await duplicate(store,u,n,r.id);if(dup)return resp(409,{error:'Já existe outra fatura com este número para o mesmo fornecedor/hotel.'});n.history=(r.history||[]).concat([audit(u,'Atualizou fatura',clean(p.comment,800))]);await save(store,n);return ok({data:publicR(n)})}
if(action==='upload'){const name=clean(p.name,220),type=clean(p.type,120),base64=String(p.base64||'').replace(/^data:[^;]+;base64,/,''),buf=Buffer.from(base64,'base64');if(!name||!buf.length||type!=='application/pdf')return bad('Carregue um PDF válido.');if(buf.length>4*1024*1024)return resp(413,{error:'O PDF pode ter no máximo 4 MB.'});await store.setJSON(fileKey(r.id),{base64,type,name});r.file={name,type,size:buf.length,createdAt:new Date().toISOString()};r.history=(r.history||[]).concat([audit(u,'Adicionou PDF',name)]);await save(store,r);return ok({data:publicR(r)})}
if(action==='delete'){if(!direction(u))return forbid('A eliminação de faturas está reservada à Direção de Operações.');await store.delete(key(r.id));try{await store.delete(fileKey(r.id))}catch(e){}return ok({deleted:true})}
return bad('Ação desconhecida.')}catch(e){console.error('energy:',e);return resp(500,{error:e.message||'Erro interno no módulo de Energia.'})}};