const { getStore, connectLambda }=require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes',RP='ops-energy-invoice/',FP='ops-energy-extra-file/';
const HEAD={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const resp=(c,b)=>({statusCode:c,headers:HEAD,body:JSON.stringify(b)}),ok=b=>resp(200,b),bad=m=>resp(400,{error:m}),forbid=m=>resp(403,{error:m}),unauth=()=>resp(401,{error:'Sessão inválida ou expirada.'}),nf=()=>resp(404,{error:'Fatura ou documento não encontrado.'});
const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n),norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/^(HOTEL\s+)?VILA\s+GALE\s+/,'').replace(/^VG(C)?\s+/,'').replace(/^COLLECTION\s+/,'').replace(/\s+/g,' ').trim(),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_');
const role=u=>String(u?.role||'diretor').toLowerCase().replace('admin','direcao').replace('director','diretor'),direction=u=>role(u)==='direcao';
function hotels(u){if(direction(u))return['*'];const a=Array.isArray(u?.hotels)?u.hotels:(u?.hotel&&u.hotel!=='*'?[u.hotel]:[]);return[...new Set(a.map(x=>clean(x,120)).filter(Boolean))]}
const canHotel=(u,h)=>direction(u)||hotels(u).some(x=>norm(x)===norm(h)),canModule=u=>direction(u)||(Array.isArray(u?.modules)&&u.modules.includes('energy'));
function from64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function verify(store,t){try{const p=String(t||'').split('.');if(p.length!==2)return null;const sec=(await store.get('_auth-secret-v1',{type:'json'}))?.value;if(!sec)return null;const exp=crypto.createHmac('sha256',Buffer.from(sec,'base64')).update(p[0]).digest(),act=from64(p[1]);if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const x=JSON.parse(from64(p[0]).toString('utf8'));if(!x.sub||x.exp<=Math.floor(Date.now()/1000))return null;const us=(await store.get('users',{type:'json'}))||{},u=us[x.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(x.av||1))return null;return u}catch(e){return null}}
const bearer=e=>{const h=e.headers?.authorization||e.headers?.Authorization||'',m=String(h).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
const invoiceKey=id=>RP+safe(id),metaKey=(id,f)=>FP+safe(id)+'/meta/'+safe(f),blobKey=(id,f)=>FP+safe(id)+'/blob/'+safe(f);
async function invoice(store,id){return await store.get(invoiceKey(id),{type:'json'})||null}
async function listFiles(store,id){const l=await store.list({prefix:FP+safe(id)+'/meta/'}),out=[];for(const b of l.blobs||[]){const x=await store.get(b.key,{type:'json'});if(x)out.push(x)}return out.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}
exports.handler=async event=>{connectLambda(event);if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:HEAD,body:''};const store=getStore(STORE);try{const u=await verify(store,bearer(event));if(!u)return unauth();if(!canModule(u))return forbid('O seu perfil não tem acesso ao módulo de Energia.');const q=event.queryStringParameters||{},action=clean(q.action||'list',40),id=clean(q.id,160);if(!id)return bad('Identifique a fatura.');const r=await invoice(store,id);if(!r||!canHotel(u,r.hotel))return nf();
if(event.httpMethod==='GET'&&action==='list'){const data=await listFiles(store,id);return ok({data,total:data.length})}
if(event.httpMethod==='GET'&&action==='file'){const fid=clean(q.file,160),m=await store.get(metaKey(id,fid),{type:'json'}),d=await store.get(blobKey(id,fid),{type:'json'});if(!m||!d?.base64)return nf();return ok({data:{...m,base64:d.base64}})}
if(event.httpMethod!=='POST')return resp(405,{error:'Método não permitido.'});let p={};try{p=JSON.parse(event.body||'{}')}catch(e){return bad('JSON inválido.')}
if(action==='upload'){const name=clean(p.name,220),type=clean(p.type,120),base64=String(p.base64||'').replace(/^data:[^;]+;base64,/,''),buf=Buffer.from(base64,'base64');if(!name||!buf.length||type!=='application/pdf')return bad('Carregue um PDF válido.');if(buf.length>4*1024*1024)return resp(413,{error:'Cada PDF pode ter no máximo 4 MB.'});const current=await listFiles(store,id);if(current.length>=9)return bad('Cada fatura pode ter no máximo 10 PDFs no total.');const fid='pdf_'+Date.now().toString(36)+'_'+crypto.randomBytes(4).toString('hex'),meta={id:fid,name,type,size:buf.length,createdAt:new Date().toISOString(),createdBy:{user:u.user,name:u.name||u.user,profile:role(u)}};await store.setJSON(blobKey(id,fid),{base64});await store.setJSON(metaKey(id,fid),meta);return ok({data:meta,total:current.length+1})}
if(action==='delete'){const fid=clean(p.file||q.file,160),m=await store.get(metaKey(id,fid),{type:'json'});if(!m)return nf();await store.delete(metaKey(id,fid));await store.delete(blobKey(id,fid));return ok({deleted:true})}
return bad('Ação desconhecida.')}catch(e){console.error('energy-files:',e);return resp(500,{error:e.message||'Erro interno nos documentos de Energia.'})}};