const {getStore,connectLambda}=require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes';
const SNAP='_recovery-snapshot/';
const DATA='_recovery-data/';
const MAX_SNAPSHOTS=20;
const CONCURRENCY=32;
const CHUNK_MAX_ITEMS=120;
const CHUNK_MAX_BYTES=900*1024;
const H={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store'};
const res=(c,b)=>({statusCode:c,headers:H,body:JSON.stringify(b)}),ok=b=>res(200,b),bad=m=>res(400,{error:m}),forbid=m=>res(403,{error:m}),unauth=()=>res(401,{error:'Sessão inválida ou expirada.'});
const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n);
const safe=v=>clean(v,180).replace(/[^a-zA-Z0-9_.-]/g,'_');
function b64u(s){s=String(s||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function auth(store,e){try{const m=String(e.headers?.authorization||e.headers?.Authorization||'').match(/^Bearer\s+(.+)$/i);if(!m)return null;const p=m[1].split('.'),sec=await store.get('_auth-secret-v1',{type:'json'});if(p.length!==2||!sec?.value)return null;const actual=b64u(p[1]),expected=crypto.createHmac('sha256',Buffer.from(sec.value,'base64')).update(p[0]).digest();if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return null;const pay=JSON.parse(b64u(p[0]).toString('utf8'));if(!pay.sub||pay.exp<=Math.floor(Date.now()/1000))return null;const users=await store.get('users',{type:'json'})||{},u=users[pay.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(pay.av||1))return null;return u}catch(e){return null}}
const direction=u=>['direcao','admin'].includes(String(u?.role||'').toLowerCase());
async function listAll(store,prefix=''){let out=[],cursor;do{const q={prefix};if(cursor)q.cursor=cursor;const r=await store.list(q);out=out.concat(Array.isArray(r?.blobs)?r.blobs:[]);cursor=r?.nextCursor||r?.cursor||null}while(cursor);return out}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i],i)}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,items.length))},worker));return out}
const PREFIXES=[
 'mes-','mesacum-','hotel-','occ-','ig-','rd-','piu-','hotelxlsx-','cdbatch-','settings-','hotelsheet-',
 'ops-action/','ops-agenda/','ops-doc-meta/','ops-doc-data/','ops-hotel-profile/','ops-approval/','ops-scenario/',
 'ops-process/','ops-process-file/','ops-process-counter/',
 'ops-cityledger-snapshot/','ops-cityledger-data/','ops-cityledger-diligence/','ops-housekeeping-','ops-ab-','ops-reputation-semester-','ops-cityledger-email-templates',
 'ops-complaint-record/','ops-complaint-file/','ops-complaint-counter/','ops-lostfound-record/','ops-lostfound-file/','ops-lostfound-counter/','ops-lostfound-email/',
 'ops-refund/','ops-refund-file/','ops-budget-record/','ops-budget-file/','ops-budget-counter/','ops-intervention-record/',
 'ops-energy-invoice/','ops-energy-file/','ops-energy-extra-file/','ops-unbilled/','ops-unbilled-file/','ops-hr-balances-snapshot/'
];
const EXACT=new Set(['index','meta','notas','cdmeta','targets-rules','ops-hr-balances-v1']);
function baseKey(key){let k=String(key||'');if(k.startsWith('market/brasil/'))k=k.slice('market/brasil/'.length);return k}
function recoverable(key){const k=baseKey(key);if(EXACT.has(k))return true;return PREFIXES.some(p=>k.startsWith(p))}
function category(key){const k=baseKey(key);if(k.startsWith('ops-process'))return'Workflow de Aprovações';if(k.startsWith('ops-energy'))return'Energia & Consumos';if(k.startsWith('ops-unbilled'))return'Contas por Faturar';if(k.startsWith('ops-refund'))return'Devoluções';if(k.startsWith('ops-complaint'))return'Reclamações';if(k.startsWith('ops-lostfound'))return'Perdidos & Achados';if(k.startsWith('ops-budget')||k.startsWith('ops-intervention'))return'Orçamentos / Intervenções';if(k.startsWith('ops-hr-balances'))return'Banco de Horas & Férias';if(k.startsWith('ops-cityledger'))return'City Ledger';if(k.startsWith('ops-housekeeping'))return'Housekeeping & Têxtil';if(k.startsWith('ops-ab-'))return'Compras & A&B';if(k.startsWith('ops-action/'))return'Ações';if(k.startsWith('ops-agenda/'))return'Agenda';if(k.startsWith('ops-doc-'))return'Documentos';if(k.startsWith('hotelsheet-'))return'Comentários Fecho do Mês';if(k.startsWith('mes-')||k.startsWith('mesacum-'))return'P&L';if(k.startsWith('occ-'))return'Ocupação';if(k.startsWith('rd-'))return'Receita Detalhada';if(k.startsWith('ig-'))return'Instagram';if(k.startsWith('hotel-')||k.startsWith('ops-reputation'))return'Reputação';if(k==='targets-rules'||k.startsWith('settings-'))return'Configuração';return'Outros'}
const snapKey=id=>SNAP+safe(id),chunkKey=(id,n)=>DATA+safe(id)+'/chunk-'+String(n).padStart(4,'0');
async function snapshots(store){const blobs=await listAll(store,SNAP),rows=await mapLimit(blobs,CONCURRENCY,async b=>{try{return await store.get(b.key,{type:'json'})}catch(e){return null}});return rows.filter(x=>x&&x.id&&x.status==='ready').sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))}
async function deleteSnapshot(store,id){const m=await store.get(snapKey(id),{type:'json'});if(!m)return false;if(Array.isArray(m.chunks))await mapLimit(m.chunks,CONCURRENCY,c=>store.delete(c.key));else if(Array.isArray(m.entries))await mapLimit(m.entries,CONCURRENCY,e=>e?.backupKey?store.delete(e.backupKey):null);await store.delete(snapKey(id));return true}
async function prune(store){const rows=await snapshots(store);if(rows.length<=MAX_SNAPSHOTS)return;const victims=rows.slice(MAX_SNAPSHOTS);await mapLimit(victims,6,v=>deleteSnapshot(store,v.id))}
function pack(items){const chunks=[];let cur=[],bytes=0;for(const it of items){if(cur.length&&(cur.length>=CHUNK_MAX_ITEMS||bytes+it.bytes>CHUNK_MAX_BYTES)){chunks.push(cur);cur=[];bytes=0}cur.push(it);bytes+=it.bytes}if(cur.length)chunks.push(cur);return chunks}
async function createSnapshot(store,u,opt={}){const id='bkp_'+Date.now().toString(36)+'_'+crypto.randomBytes(5).toString('hex'),all=await listAll(store,''),source=all.filter(x=>recoverable(x.key));const read=await mapLimit(source,CONCURRENCY,async item=>{let raw=await store.get(item.key,{type:'text'});if(raw==null)return null;if(typeof raw!=='string')raw=JSON.stringify(raw);return{key:item.key,raw,bytes:Buffer.byteLength(raw,'utf8'),category:category(item.key)}});const items=read.filter(Boolean),groups=pack(items),chunks=[];await mapLimit(groups,8,async(g,i)=>{const key=chunkKey(id,i);await store.setJSON(key,{items:g.map(x=>({key:x.key,raw:x.raw}))});chunks[i]={key,count:g.length,bytes:g.reduce((s,x)=>s+x.bytes,0)}});const counts={};let size=0;for(const x of items){counts[x.category]=(counts[x.category]||0)+1;size+=x.bytes}const m={id,status:'ready',format:2,kind:opt.kind==='pre_restore'?'pre_restore':'manual',createdAt:new Date().toISOString(),user:u.user,name:u.name||u.user,role:u.role,note:clean(opt.note,500),sourceSnapshotId:clean(opt.sourceSnapshotId,120),items:items.length,sizeBytes:size,resourceCounts:counts,chunks,appVersion:'36.1',buildVersion:'35.6'};await store.setJSON(snapKey(id),m);await prune(store);return m}
async function readPayloads(store,m){if(Array.isArray(m.chunks)&&m.chunks.length){const parts=await mapLimit(m.chunks,CONCURRENCY,async c=>{const d=await store.get(c.key,{type:'json'});if(!d||!Array.isArray(d.items))throw new Error('Snapshot incompleto.');return d.items});return parts.flat().filter(x=>x&&x.key&&recoverable(x.key)&&typeof x.raw==='string')}const entries=Array.isArray(m.entries)?m.entries:[];return(await mapLimit(entries,CONCURRENCY,async e=>{if(!e?.key||!e?.backupKey||!recoverable(e.key))return null;let raw=await store.get(e.backupKey,{type:'text'});if(raw==null)throw new Error('Snapshot incompleto: falta '+e.key);if(typeof raw!=='string')raw=JSON.stringify(raw);return{key:e.key,raw}})).filter(Boolean)}
async function restore(store,u,id){const m=await store.get(snapKey(id),{type:'json'});if(!m||m.status!=='ready')throw new Error('Snapshot não encontrado.');const payloads=await readPayloads(store,m);if(!payloads.length)throw new Error('Snapshot sem dados recuperáveis.');const safety=await createSnapshot(store,u,{kind:'pre_restore',note:'Cópia automática antes de repor '+id,sourceSnapshotId:id});const cur=(await listAll(store,'')).filter(x=>recoverable(x.key));await mapLimit(cur,CONCURRENCY,x=>store.delete(x.key));await mapLimit(payloads,CONCURRENCY,x=>store.set(x.key,x.raw));return{restoredItems:payloads.length,removedItems:cur.length,safety}}
exports.handler=async e=>{connectLambda(e);if(e.httpMethod==='OPTIONS')return{statusCode:204,headers:H,body:''};const store=getStore(STORE);try{const u=await auth(store,e);if(!u)return unauth();if(!direction(u))return forbid('Backup & Recuperação está reservado à Direção.');const action=clean(e.queryStringParameters?.action||'list',40);let p={};if(e.httpMethod==='POST'){try{p=JSON.parse(e.body||'{}')}catch{return bad('JSON inválido.')}}if(e.httpMethod==='GET'&&action==='list'){const rows=await snapshots(store);return ok({data:rows.map(x=>({id:x.id,kind:x.kind,createdAt:x.createdAt,user:x.user,name:x.name,note:x.note,items:x.items,sizeBytes:x.sizeBytes,resourceCounts:x.resourceCounts,sourceSnapshotId:x.sourceSnapshotId,appVersion:x.appVersion,buildVersion:x.buildVersion,format:x.format||1})),total:rows.length})}if(e.httpMethod==='POST'&&action==='create'){const m=await createSnapshot(store,u,{note:p.note,kind:'manual'});return ok({data:{id:m.id,kind:m.kind,createdAt:m.createdAt,name:m.name,note:m.note,items:m.items,sizeBytes:m.sizeBytes,resourceCounts:m.resourceCounts}})}if(e.httpMethod==='POST'&&action==='restore'){if(String(p.confirmation||'').trim().toUpperCase()!=='REPOR')return bad('Confirmação inválida. Escreva REPOR.');const id=safe(p.id);if(!id)return bad('Snapshot obrigatório.');const r=await restore(store,u,id);return ok({restoredItems:r.restoredItems,removedItems:r.removedItems,safetySnapshot:{id:r.safety.id,createdAt:r.safety.createdAt}})}if(e.httpMethod==='POST'&&action==='delete'){if(String(p.confirmation||'').trim().toUpperCase()!=='APAGAR')return bad('Confirmação inválida. Escreva APAGAR.');const id=safe(p.id);if(!id)return bad('Snapshot obrigatório.');if(!await deleteSnapshot(store,id))return res(404,{error:'Snapshot não encontrado.'});return ok({deleted:true})}return res(405,{error:'Método não permitido.'})}catch(err){console.error('recovery-v36:',err);return res(500,{error:err.message||'Erro interno no Backup & Recuperação.'})}};