const {getStore,connectLambda}=require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes',RP='ops-refund/',FP='ops-refund-file/';
const H={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store'};
const resp=(c,b)=>({statusCode:c,headers:H,body:JSON.stringify(b)}),ok=b=>resp(200,b),bad=m=>resp(400,{error:m}),forbid=m=>resp(403,{error:m}),unauth=()=>resp(401,{error:'Sessão inválida ou expirada.'}),nf=()=>resp(404,{error:'Devolução não encontrada.'});
const clean=(v,n=1000)=>String(v==null?'':v).trim().slice(0,n),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_'),norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/^(HOTEL\s+)?VILA\s+GALE\s+/,'').replace(/^VG(C)?\s+/,'').replace(/^COLLECTION\s+/,'').replace(/\s+/g,' ').trim();
const role=u=>String(u?.role||'diretor').toLowerCase().replace('admin','direcao').replace('director','diretor'),direction=u=>role(u)==='direcao';
function hotels(u){if(direction(u))return['*'];const a=Array.isArray(u?.hotels)?u.hotels:(u?.hotel&&u.hotel!=='*'?[u.hotel]:[]);return[...new Set(a.map(x=>clean(x,120)).filter(Boolean))]}
const canHotel=(u,h)=>direction(u)||hotels(u).some(x=>norm(x)===norm(h)),canModule=u=>direction(u)||(Array.isArray(u?.modules)&&u.modules.includes('refunds'));
function from64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function verify(store,t){try{const p=String(t||'').split('.');if(p.length!==2)return null;const sec=(await store.get('_auth-secret-v1',{type:'json'}))?.value;if(!sec)return null;const exp=crypto.createHmac('sha256',Buffer.from(sec,'base64')).update(p[0]).digest(),act=from64(p[1]);if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const x=JSON.parse(from64(p[0]).toString('utf8'));if(!x.sub||x.exp<=Math.floor(Date.now()/1000))return null;const us=(await store.get('users',{type:'json'}))||{},u=us[x.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(x.av||1))return null;return u}catch(e){return null}}
const bearer=e=>{const h=e.headers?.authorization||e.headers?.Authorization||'',m=String(h).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
const key=id=>RP+safe(id),fileKey=(id,f)=>FP+safe(id)+'/'+safe(f),audit=(u,a,d='')=>({at:new Date().toISOString(),user:u.user,name:u.name||u.user,profile:role(u),action:a,detail:clean(d,1500)});
async function get(store,id){return await store.get(key(id),{type:'json'})||null}async function save(store,r){r.updatedAt=new Date().toISOString();await store.setJSON(key(r.id),r);return r}
async function list(store,u){const l=await store.list({prefix:RP}),out=[];for(const b of l.blobs||[]){const r=await store.get(b.key,{type:'json'});if(r&&canHotel(u,r.hotel))out.push(r)}return out.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
function makeCode(h){const p=norm(h).replace(/[^A-Z0-9]/g,'').slice(0,3)||'VG';return 'DEV-'+p+'-'+Date.now().toString(36).toUpperCase().slice(-6)}
function amount(v){let s=String(v??'').replace(/\s/g,'').replace(/€/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
exports.handler=async event=>{connectLambda(event);if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:H,body:''};const store=getStore(STORE);try{const u=await verify(store,bearer(event));if(!u)return unauth();if(!canModule(u))return forbid('Sem acesso ao módulo de Devoluções.');const q=event.queryStringParameters||{},action=clean(q.action||'list',40);
if(event.httpMethod==='GET'&&action==='list')return ok({data:await list(store,u)});
if(event.httpMethod==='GET'&&action==='file'){const r=await get(store,clean(q.id,160));if(!r||!canHotel(u,r.hotel))return nf();const f=(r.files||[]).find(x=>x.id===clean(q.file,160));if(!f)return nf();const d=await store.get(fileKey(r.id,f.id),{type:'json'});return d?.base64?ok({data:{...f,base64:d.base64}}):nf()}
if(event.httpMethod!=='POST')return resp(405,{error:'Método não permitido.'});let p={};try{p=JSON.parse(event.body||'{}')}catch(e){return bad('JSON inválido.')}
if(action==='create'){const h=clean(p.hotel,120);if(!h||!canHotel(u,h))return forbid('Hotel inválido ou sem autorização.');const r={id:'REF-'+Date.now().toString(36)+'-'+crypto.randomBytes(3).toString('hex'),code:makeCode(h),hotel:h,complaintCode:clean(p.complaintCode,120),customerName:clean(p.customerName,180),customerEmail:clean(p.customerEmail,180),reservation:clean(p.reservation,100),room:clean(p.room,40),reason:clean(p.reason,3000),amount:amount(p.amount),refundMethod:clean(p.refundMethod,120),paymentReference:clean(p.paymentReference,180),department:clean(p.department,120),responsible:clean(p.responsible,180),status:'Rascunho',archived:false,files:[],approval:null,daf:null,processed:null,createdAt:new Date().toISOString(),createdBy:{user:u.user,name:u.name||u.user,profile:role(u)},history:[audit(u,'Criou devolução')]};if(!r.customerName||!r.reason||r.amount<=0)return bad('Preencha cliente, motivo e valor da devolução.');await save(store,r);return ok({data:r})}
const id=clean(p.id||q.id,160),r=await get(store,id);if(!r||!canHotel(u,r.hotel))return nf();
if(action==='update'){if(r.archived)return bad('Processo arquivado.');if(['A aguardar decisão DO','Aprovada','A aguardar DAF','Processada','Concluída'].includes(r.status)&&!direction(u))return bad('O processo já não pode ser editado pelo hotel.');['customerName','customerEmail','reservation','room','reason','refundMethod','paymentReference','department','responsible','complaintCode'].forEach(k=>{if(k in p)r[k]=clean(p[k],k==='reason'?3000:180)});if('amount'in p)r.amount=amount(p.amount);r.history=(r.history||[]).concat([audit(u,'Atualizou devolução',clean(p.comment,800))]);await save(store,r);return ok({data:r})}
if(action==='submit'){if(r.status!=='Rascunho'&&r.status!=='A aguardar esclarecimentos')return bad('Estado inválido para submissão.');if(!r.customerName||!r.reason||r.amount<=0)return bad('Dados obrigatórios em falta.');r.status='A aguardar decisão DO';r.history.push(audit(u,'Submeteu à decisão DO',clean(p.comment,800)));await save(store,r);return ok({data:r})}
if(action==='decide'){if(!direction(u))return forbid('A decisão está reservada à Direção de Operações.');if(r.status!=='A aguardar decisão DO')return bad('Processo não está a aguardar decisão DO.');const d=clean(p.decision,40),c=clean(p.comment,1200);if(!c)return bad('Comentário obrigatório.');if(d==='Aprovar'){r.status='A aguardar DAF';r.approval={decision:'Aprovada',comment:c,at:new Date().toISOString(),user:u.user,name:u.name||u.user};r.daf={pending:true,sentAt:null,processedAt:null}}else if(d==='Recusar'){r.status='Recusada';r.approval={decision:'Recusada',comment:c,at:new Date().toISOString(),user:u.user,name:u.name||u.user}}else if(d==='Solicitar esclarecimentos'){r.status='A aguardar esclarecimentos';r.approval={decision:'Esclarecimentos',comment:c,at:new Date().toISOString(),user:u.user,name:u.name||u.user}}else return bad('Decisão inválida.');r.history.push(audit(u,'Decisão DO',d+' · '+c));await save(store,r);return ok({data:r})}
if(action==='markDaf'){if(!direction(u))return forbid('Ação reservada à Direção de Operações.');if(r.status!=='A aguardar DAF')return bad('Processo não está a aguardar DAF.');r.daf={...(r.daf||{}),pending:false,sentAt:new Date().toISOString(),reference:clean(p.reference,500)};r.history.push(audit(u,'Encaminhou para DAF',clean(p.reference,800)));await save(store,r);return ok({data:r})}
if(action==='processed'){if(!direction(u))return forbid('Ação reservada à Direção de Operações.');if(r.status!=='A aguardar DAF')return bad('Estado inválido.');r.status='Processada';r.processed={at:new Date().toISOString(),reference:clean(p.reference,500),user:u.user,name:u.name||u.user};r.history.push(audit(u,'Registou devolução processada',clean(p.reference,800)));await save(store,r);return ok({data:r})}
if(action==='complete'){if(r.status!=='Processada')return bad('Só uma devolução processada pode ser concluída.');r.status='Concluída';r.history.push(audit(u,'Concluiu devolução',clean(p.comment,800)));await save(store,r);return ok({data:r})}
if(action==='archive'){if(r.status!=='Concluída')return bad('Só uma devolução concluída pode ser arquivada.');r.status='Arquivada';r.archived=true;r.history.push(audit(u,'Arquivou devolução'));await save(store,r);return ok({data:r})}
if(action==='upload'){const name=clean(p.name,220),type=clean(p.type,120),base64=String(p.base64||'').replace(/^data:[^;]+;base64,/,''),buf=Buffer.from(base64,'base64');if(!name||!buf.length)return bad('Ficheiro inválido.');if(buf.length>5*1024*1024)return resp(413,{error:'Máximo 5 MB por ficheiro.'});if((r.files||[]).length>=10)return bad('Máximo 10 anexos.');const fid='f_'+Date.now().toString(36)+'_'+crypto.randomBytes(3).toString('hex'),meta={id:fid,name,type,size:buf.length,createdAt:new Date().toISOString()};await store.setJSON(fileKey(r.id,fid),{base64});r.files=(r.files||[]).concat([meta]);r.history.push(audit(u,'Adicionou anexo',name));await save(store,r);return ok({data:r})}
if(action==='deletefile'){const fid=clean(p.file,160),f=(r.files||[]).find(x=>x.id===fid);if(!f)return nf();r.files=r.files.filter(x=>x.id!==fid);try{await store.delete(fileKey(r.id,fid))}catch(e){}r.history.push(audit(u,'Removeu anexo',f.name));await save(store,r);return ok({data:r})}
return bad('Ação desconhecida.')}catch(e){console.error('refunds:',e);return resp(500,{error:e.message||'Erro interno em Devoluções.'})}};