const {getStore,connectLambda}=require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes',RP='ops-unbilled/',FP='ops-unbilled-file/';
const HEAD={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store'};
const resp=(c,b)=>({statusCode:c,headers:HEAD,body:JSON.stringify(b)}),ok=b=>resp(200,b),bad=m=>resp(400,{error:m}),forbid=m=>resp(403,{error:m}),unauth=()=>resp(401,{error:'Sessão inválida ou expirada.'}),nf=()=>resp(404,{error:'Registo não encontrado.'});
const clean=(v,n=500)=>String(v==null?'':v).trim().slice(0,n),norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/^(HOTEL\s+)?VILA\s+GALE\s+/,'').replace(/^VG(C)?\s+/,'').replace(/^COLLECTION\s+/,'').replace(/\s+/g,' ').trim(),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_');
const role=u=>String(u?.role||'diretor').toLowerCase().replace('admin','direcao').replace('director','diretor'),direction=u=>role(u)==='direcao';
function hotels(u){if(direction(u))return['*'];const a=Array.isArray(u?.hotels)?u.hotels:(u?.hotel&&u.hotel!=='*'?[u.hotel]:[]);return [...new Set(a.map(x=>clean(x,120)).filter(Boolean))]}
const canHotel=(u,h)=>direction(u)||hotels(u).some(x=>norm(x)===norm(h)),canModule=u=>direction(u)||(Array.isArray(u?.modules)&&u.modules.includes('unbilled'));
function from64(s){s=String(s).replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function verify(store,t){try{const p=String(t||'').split('.');if(p.length!==2)return null;const sec=(await store.get('_auth-secret-v1',{type:'json'}))?.value;if(!sec)return null;const exp=crypto.createHmac('sha256',Buffer.from(sec,'base64')).update(p[0]).digest(),act=from64(p[1]);if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const x=JSON.parse(from64(p[0]).toString('utf8'));if(!x.sub||x.exp<=Math.floor(Date.now()/1000))return null;const us=(await store.get('users',{type:'json'}))||{},u=us[x.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(x.av||1))return null;return u}catch(e){return null}}
const bearer=e=>{const h=e.headers?.authorization||e.headers?.Authorization||'',m=String(h).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():''};
const key=id=>RP+safe(id),fileKey=(id,f)=>FP+safe(id)+'/'+safe(f),audit=(u,a,d='')=>({at:new Date().toISOString(),user:u.user,name:u.name||u.user,profile:role(u),action:a,detail:clean(d,1200)});
async function get(store,id){return await store.get(key(id),{type:'json'})||null}async function save(store,r){r.updatedAt=new Date().toISOString();await store.setJSON(key(r.id),r);return r}
function summary(r){return {id:r.id,code:r.code,hotel:r.hotel,client:r.client,reference:r.reference,reservation:r.reservation,referenceDate:r.referenceDate,amount:r.amount,reason:r.reason,responsible:r.responsible,department:r.department,status:r.status,invoiceNo:r.invoiceNo,invoiceDate:r.invoiceDate,sentDate:r.sentDate,paidDate:r.paidDate,notes:r.notes,createdAt:r.createdAt,updatedAt:r.updatedAt}}
async function list(store,u){
  const l=await store.list({prefix:RP});
  const blobs=l.blobs||[];
  const out=[];
  const CHUNK=250;
  for(let i=0;i<blobs.length;i+=CHUNK){
    const part=blobs.slice(i,i+CHUNK);
    const got=await Promise.all(part.map(b=>store.get(b.key,{type:'json'}).catch(()=>null)));
    for(const r of got)if(r&&canHotel(u,r.hotel))out.push(summary(r));
  }
  return out.sort((a,b)=>String(b.referenceDate||b.createdAt).localeCompare(String(a.referenceDate||a.createdAt)));
}
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').replace(/\s/g,'').replace(/€/g,'');if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function build(p,u,old){return {...(old||{}),hotel:clean(p.hotel??old?.hotel,120),client:clean(p.client??old?.client,220),reference:clean(p.reference??old?.reference,160),reservation:clean(p.reservation??old?.reservation,120),referenceDate:clean(p.referenceDate??old?.referenceDate,30),amount:num(p.amount??old?.amount),reason:clean(p.reason??old?.reason,2000),responsible:clean(p.responsible??old?.responsible,180),department:clean(p.department??old?.department,140),status:clean((p.status??old?.status)||'Por faturar',50),invoiceNo:clean(p.invoiceNo??old?.invoiceNo,120),invoiceDate:clean(p.invoiceDate??old?.invoiceDate,30),sentDate:clean(p.sentDate??old?.sentDate,30),paidDate:clean(p.paidDate??old?.paidDate,30),notes:clean(p.notes??old?.notes,2500),updatedBy:{user:u.user,name:u.name||u.user,profile:role(u)}}}
const STATES=['Por faturar','Em validação','Fatura emitida','Enviada','Recebida/Paga','Anulada'];
exports.handler=async event=>{connectLambda(event);if(event.httpMethod==='OPTIONS')return{statusCode:204,headers:HEAD,body:''};const store=getStore(STORE);try{const u=await verify(store,bearer(event));if(!u)return unauth();if(!canModule(u))return forbid('O seu perfil não tem acesso ao módulo Contas por Faturar.');const q=event.queryStringParameters||{},action=clean(q.action||'list',40);
if(event.httpMethod==='GET'&&action==='list')return ok({data:await list(store,u)});
if(event.httpMethod==='GET'&&action==='get'){const r=await get(store,clean(q.id,160));if(!r||!canHotel(u,r.hotel))return nf();return ok({data:r})}
if(event.httpMethod==='GET'&&action==='file'){const r=await get(store,clean(q.id,160));if(!r||!canHotel(u,r.hotel))return nf();const f=(r.files||[]).find(x=>x.id===q.file);if(!f)return nf();const d=await store.get(fileKey(r.id,f.id),{type:'json'});return d?.base64?ok({data:{...f,base64:d.base64}}):nf()}
if(event.httpMethod!=='POST')return resp(405,{error:'Método não permitido.'});let p={};try{p=JSON.parse(event.body||'{}')}catch(e){return bad('JSON inválido.')}
if(action==='create'){const r=build(p,u);if(!r.hotel||!r.client||!r.referenceDate||!r.amount)return bad('Preencha hotel, cliente, data de referência e valor.');if(!canHotel(u,r.hotel))return forbid('Sem acesso ao hotel indicado.');if(!STATES.includes(r.status))r.status='Por faturar';r.id='CPF-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();r.code='CPF-'+String(Date.now()).slice(-8);r.createdAt=new Date().toISOString();r.createdBy={user:u.user,name:u.name||u.user,profile:role(u)};r.files=[];r.history=[audit(u,'Criou conta por faturar',`${r.client} · ${r.amount}`)];await save(store,r);return ok({data:r})}
if(action==='batch'){const items=Array.isArray(p.items)?p.items:[];if(!items.length)return bad('Sem registos para importar.');let created=0,errors=[];for(let i=0;i<Math.min(items.length,1000);i++){try{const r=build(items[i],u);if(!r.hotel||!r.client||!r.referenceDate||!r.amount||!canHotel(u,r.hotel)){errors.push({row:i+2,error:'Dados obrigatórios/hotel inválido'});continue}r.id='CPF-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();r.code='CPF-'+String(Date.now()+i).slice(-8);r.status=STATES.includes(r.status)?r.status:'Por faturar';r.createdAt=new Date().toISOString();r.createdBy={user:u.user,name:u.name||u.user,profile:role(u)};r.files=[];r.history=[audit(u,'Importou conta por faturar','Excel/CSV')];await save(store,r);created++}catch(e){errors.push({row:i+2,error:e.message})}}return ok({created,errors:errors.slice(0,50)})}
const id=clean(p.id||q.id,160),r=await get(store,id);if(!r||!canHotel(u,r.hotel))return nf();
if(action==='update'){const n=build(p,u,r);if(!canHotel(u,n.hotel))return forbid('Sem acesso ao hotel indicado.');if(!STATES.includes(n.status))return bad('Estado inválido.');n.history=(r.history||[]).concat([audit(u,'Atualizou conta por faturar',clean(p.comment,800))]);await save(store,n);return ok({data:n})}
if(action==='comment'){const text=clean(p.text,1600);if(!text)return bad('Escreva a diligência/comentário.');r.history=(r.history||[]).concat([audit(u,'Diligência',text)]);await save(store,r);return ok({data:r})}
if(action==='upload'){const name=clean(p.name,220),type=clean(p.type,120),base64=String(p.base64||'').replace(/^data:[^;]+;base64,/,''),buf=Buffer.from(base64,'base64');if(!name||!buf.length)return bad('Ficheiro inválido.');if(buf.length>5*1024*1024)return resp(413,{error:'Máximo 5 MB por ficheiro.'});const fid='f_'+Date.now().toString(36)+'_'+crypto.randomBytes(3).toString('hex'),meta={id:fid,name,type,size:buf.length,createdAt:new Date().toISOString()};await store.setJSON(fileKey(r.id,fid),{base64});r.files=(r.files||[]).concat([meta]);r.history=(r.history||[]).concat([audit(u,'Adicionou anexo',name)]);await save(store,r);return ok({data:r})}
if(action==='delete'){if(!direction(u))return forbid('A eliminação está reservada à Direção de Operações.');for(const f of r.files||[]){try{await store.delete(fileKey(r.id,f.id))}catch(e){}}await store.delete(key(r.id));return ok({deleted:true})}
return bad('Ação desconhecida.')}catch(e){console.error('unbilled:',e);return resp(500,{error:e.message||'Erro interno em Contas por Faturar.'})}};