const {getStore,connectLambda}=require('@netlify/blobs');
const crypto=require('crypto');
const STORE='vg-dashboard-operacoes';
const PREFIX={complaint:'ops-complaint-record/',refund:'ops-refund/',budget:'ops-budget-record/'};
const HEAD={'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const out=(c,b)=>({statusCode:c,headers:HEAD,body:JSON.stringify(b)}),ok=b=>out(200,b),bad=m=>out(400,{error:m}),forbid=m=>out(403,{error:m}),unauth=()=>out(401,{error:'Sessão inválida ou expirada.'}),nf=()=>out(404,{error:'Processo não encontrado.'});
const clean=(v,n=1000)=>String(v==null?'':v).trim().slice(0,n),norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/^(HOTEL\s+)?VILA\s+GALE\s+/,'').replace(/^VG(C)?\s+/,'').replace(/^COLLECTION\s+/,'').replace(/\s+/g,' ').trim(),safe=v=>clean(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_.-]/g,'_');
function b64u(s){s=String(s||'').replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Buffer.from(s,'base64')}
async function auth(store,e){try{const h=e.headers?.authorization||e.headers?.Authorization||'',m=String(h).match(/^Bearer\s+(.+)$/i);if(!m)return null;const p=m[1].split('.'),sec=await store.get('_auth-secret-v1',{type:'json'});if(p.length!==2||!sec?.value)return null;const act=b64u(p[1]),exp=crypto.createHmac('sha256',Buffer.from(sec.value,'base64')).update(p[0]).digest();if(act.length!==exp.length||!crypto.timingSafeEqual(act,exp))return null;const pay=JSON.parse(b64u(p[0]).toString('utf8'));if(!pay.sub||pay.exp<=Math.floor(Date.now()/1000))return null;const users=await store.get('users',{type:'json'})||{},u=users[pay.sub];if(!u||u.active===false||Number(u.authVersion||1)!==Number(pay.av||1))return null;return u}catch{return null}}
const role=u=>String(u?.role||'').toLowerCase().replace('admin','direcao').replace('director','diretor'),isDO=u=>role(u)==='direcao';
function hotels(u){if(isDO(u))return['*'];const a=Array.isArray(u?.hotels)?u.hotels:(u?.hotel&&u.hotel!=='*'?[u.hotel]:[]);return [...new Set(a.map(x=>clean(x,120)).filter(Boolean))]}
const canHotel=(u,h)=>isDO(u)||hotels(u).some(x=>norm(x)===norm(h));
function canType(u,type){if(isDO(u))return true;const m=Array.isArray(u?.modules)?u.modules:[];return m.includes('approvals')||m.includes('workflow')||(type==='complaint'&&m.includes('complaints'))||(type==='refund'&&m.includes('refunds'))||(type==='budget'&&m.includes('budgets'))}
async function listAll(store,prefix){let blobs=[],cursor;do{const q={prefix};if(cursor)q.cursor=cursor;const r=await store.list(q);blobs=blobs.concat(r?.blobs||[]);cursor=r?.nextCursor||r?.cursor||null}while(cursor);return blobs}
async function records(store,prefix){const blobs=await listAll(store,prefix),out=[];for(let i=0;i<blobs.length;i+=24){const vals=await Promise.all(blobs.slice(i,i+24).map(b=>store.get(b.key,{type:'json'}).catch(()=>null)));out.push(...vals.filter(Boolean))}return out}
const hist=r=>(Array.isArray(r?.history)?r.history:[]).map(h=>({at:h.at,user:h.user,name:h.name,role:h.role||h.profile,action:h.action,detail:h.detail||''}));
const files=r=>(Array.isArray(r?.files)?r.files:[]).map(f=>({id:f.id,name:f.name,type:f.type,size:f.size,createdAt:f.createdAt}));
function mapComplaint(r){return{id:'complaint:'+r.id,native:true,nativeId:r.id,type:'complaint',typeLabel:'Reclamação',code:r.code||r.id,hotel:r.hotel,title:r.customerName?('Reclamação · '+r.customerName):('Reclamação '+(r.code||'')),description:r.description||'',status:r.status||'Nova',priority:'normal',createdAt:r.createdAt,updatedAt:r.updatedAt||r.createdAt,createdBy:r.createdBy||{},archived:!!r.archived,meta:{origin:r.origin,customerName:r.customerName,customerEmail:r.customerEmail,reservation:r.reservation,room:r.room,department:r.department,compensation:r.compensation,compensationDetail:r.compensationDetail},history:hist(r),files:files(r),pendingDecision:r.status==='A aguardar decisão DO'} }
function mapRefund(r){return{id:'refund:'+r.id,native:true,nativeId:r.id,type:'refund',typeLabel:'Devolução',code:r.code||r.id,hotel:r.hotel,title:r.customerName?('Devolução · '+r.customerName):('Devolução '+(r.code||'')),description:r.reason||'',status:r.status||'Rascunho',priority:'normal',createdAt:r.createdAt,updatedAt:r.updatedAt||r.createdAt,createdBy:r.createdBy||{},archived:!!r.archived,meta:{customerName:r.customerName,customerEmail:r.customerEmail,reservation:r.reservation,room:r.room,amount:r.amount,method:r.refundMethod,department:r.department,complaintCode:r.complaintCode},history:hist(r),files:files(r),pendingDecision:r.status==='A aguardar decisão DO'} }
function mapBudget(r){const qs=(r.quotes||[]).filter(q=>!q.deleted).map(q=>({id:q.id,supplier:q.supplier,value:q.value,leadTime:q.leadTime,warranty:q.warranty,file:q.file?{id:q.file.id,name:q.file.name}:null}));return{id:'budget:'+r.id,native:true,nativeId:r.id,type:'budget',typeLabel:'Orçamento',code:r.code||r.id,hotel:r.hotel,title:r.subject||('Orçamento '+(r.code||'')),description:r.description||'',status:r.status||'Rascunho',priority:r.urgency==='Urgente'?'critical':r.urgency==='Prioritário'?'high':'normal',createdAt:r.createdAt,updatedAt:r.updatedAt||r.createdAt,createdBy:r.createdBy||{},archived:!!r.archived,meta:{category:r.category,urgency:r.urgency,department:r.department,responsible:r.owner,estimatedInvestment:r.estimatedInvestment,proposals:qs,selectedQuoteId:r.selectedQuoteId},history:hist(r),files:[],pendingDecision:r.status==='Submetido à DO'} }
async function list(store,u){const [c,d,b]=await Promise.all([canType(u,'complaint')?records(store,PREFIX.complaint):[],canType(u,'refund')?records(store,PREFIX.refund):[],canType(u,'budget')?records(store,PREFIX.budget):[]]);const rows=[...c.filter(r=>canHotel(u,r.hotel)).map(mapComplaint),...d.filter(r=>canHotel(u,r.hotel)).map(mapRefund),...b.filter(r=>canHotel(u,r.hotel)).map(mapBudget)];return rows.sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt)))}
function parseId(v){const s=clean(v,220),i=s.indexOf(':');if(i<1)return null;const type=s.slice(0,i),id=s.slice(i+1);return PREFIX[type]&&id?{type,id}:null}
const nativeKey=(type,id)=>PREFIX[type]+safe(id),audit=(u,a,d='')=>({at:new Date().toISOString(),user:u.user,name:u.name||u.user,profile:role(u),action:a,detail:clean(d,1500)});
async function getNative(store,type,id){return await store.get(nativeKey(type,id),{type:'json'})||null}
async function saveNative(store,type,r){r.updatedAt=new Date().toISOString();await store.setJSON(nativeKey(type,r.id),r);return r}
function mapped(type,r){return type==='complaint'?mapComplaint(r):type==='refund'?mapRefund(r):mapBudget(r)}
async function decide(store,u,type,r,p){if(!isDO(u))throw Object.assign(new Error('A decisão está reservada à Direção de Operações.'),{status:403});const decision=clean(p.decision,40),comment=clean(p.comment,1500);if(!['approve','reject','clarify'].includes(decision)||!comment)throw Object.assign(new Error('Decisão e comentário são obrigatórios.'),{status:400});if(type==='complaint'){
 if(r.status!=='A aguardar decisão DO')throw Object.assign(new Error('A reclamação não está a aguardar decisão DO.'),{status:400});
 const d=decision==='approve'?'Aprovar':decision==='reject'?'Recusar':'Solicitar esclarecimentos';r.approval={decision:d,comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user};r.status=decision==='approve'?'Aprovada':decision==='reject'?'Recusada':'A aguardar esclarecimentos';r.history=(r.history||[]).concat([audit(u,'Decisão DO: '+d,comment)]);
 }else if(type==='refund'){
 if(r.status!=='A aguardar decisão DO')throw Object.assign(new Error('A devolução não está a aguardar decisão DO.'),{status:400});
 if(decision==='approve'){r.status='A aguardar DAF';r.approval={decision:'Aprovada',comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user};r.daf={pending:true,sentAt:null,processedAt:null}}else if(decision==='reject'){r.status='Recusada';r.approval={decision:'Recusada',comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user}}else{r.status='A aguardar esclarecimentos';r.approval={decision:'Esclarecimentos',comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user}}r.history=(r.history||[]).concat([audit(u,'Decisão DO',decision+' · '+comment)]);
 }else{
 if(!['Submetido à DO','A aguardar esclarecimentos'].includes(r.status))throw Object.assign(new Error('O orçamento não está disponível para decisão DO.'),{status:400});
 if(decision==='approve'){const q=(r.quotes||[]).find(x=>!x.deleted&&x.id===clean(p.quoteId,140));if(!q||!q.file?.id)throw Object.assign(new Error('Selecione uma proposta completa para aprovar.'),{status:400});r.selectedQuoteId=q.id;r.approvedSupplier=q.supplier;r.approvedValue=Number(q.value);r.approval={decision:'Aprovar',comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user,quoteId:q.id};r.status='Aprovado'}else if(decision==='reject'){r.approval={decision:'Recusar',comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user};r.status='Recusado'}else{r.approval={decision:'Solicitar esclarecimentos',comment,at:new Date().toISOString(),user:u.user,name:u.name||u.user};r.status='A aguardar esclarecimentos'}r.history=(r.history||[]).concat([audit(u,'Decisão DO: '+r.approval.decision,comment)]);
 }await saveNative(store,type,r);return mapped(type,r)}
exports.handler=async e=>{connectLambda(e);if(e.httpMethod==='OPTIONS')return{statusCode:204,headers:HEAD,body:''};const store=getStore(STORE);try{const u=await auth(store,e);if(!u)return unauth();const q=e.queryStringParameters||{},action=clean(q.action||'list',50);if(e.httpMethod==='GET'&&action==='list'){const data=await list(store,u);return ok({data,total:data.length})}if(e.httpMethod!=='POST')return out(405,{error:'Método não permitido.'});let p={};try{p=JSON.parse(e.body||'{}')}catch{return bad('JSON inválido.')}const ref=parseId(p.id||q.id);if(!ref)return bad('Referência de processo inválida.');if(!canType(u,ref.type))return forbid('Sem acesso a este tipo de processo.');const r=await getNative(store,ref.type,ref.id);if(!r)return nf();if(!canHotel(u,r.hotel))return forbid('Sem acesso ao hotel deste processo.');if(action==='decision')return ok({data:await decide(store,u,ref.type,r,p)});if(action==='comment'){const text=clean(p.text,1800);if(!text)return bad('Escreva um comentário.');r.history=(r.history||[]).concat([audit(u,'Comentário Workflow',text)]);await saveNative(store,ref.type,r);return ok({data:mapped(ref.type,r)})}return bad('Ação desconhecida.')}catch(e){console.error('workflow-hub-v37:',e);return out(e.status||500,{error:e.message||'Erro interno no Workflow de Aprovações.'})}};