const assert=require('assert');
const fs=require('fs');
const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const server=fs.readFileSync(path.join(ROOT,'netlify/functions/recovery-v36.js'),'utf8');
const client=fs.readFileSync(path.join(ROOT,'assets/js/modules/backup-recovery.js'),'utf8');
new Function(server);
new Function(client);
assert(server.includes("const SNAP='_recovery-snapshot/'"),'mantém compatibilidade com manifests existentes');
assert(server.includes('listAll(store'),'lista blobs com paginação');
assert(server.includes('nextCursor')||server.includes('.cursor'),'suporta paginação do Netlify Blobs');
assert(server.includes('mapLimit'),'operações em grandes volumes usam concorrência limitada');
assert(server.includes('format:2'),'novo snapshot usa formato compacto V2');
['ops-complaint-record/','ops-lostfound-record/','ops-refund/','ops-budget-record/','ops-energy-invoice/','ops-unbilled/','ops-hr-balances-v1'].forEach(x=>assert(server.includes(x),'backup deve proteger '+x));
assert(server.includes('pre_restore'),'restore cria safety snapshot');
assert(server.includes('m.entries'),'restore mantém leitura de snapshots V1');
assert(client.includes("/.netlify/functions/recovery-v36"),'frontend deve usar função dedicada');
assert(client.includes("'recovery-list':'list'"),'frontend mapeia listagem');
assert(client.includes("'recovery-create':'create'"),'frontend mapeia criação');
assert(client.includes("'recovery-restore':'restore'"),'frontend mapeia reposição');
assert(client.includes("'recovery-delete':'delete'"),'frontend mapeia eliminação');
assert(!server.includes('setInterval(')&&!client.includes('setInterval('),'backup não deve usar polling contínuo');
console.log('✓ backup V36: função dedicada, paginação, chunks, módulos atuais e compatibilidade V1');
