const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const front=fs.readFileSync(path.join(root,'assets/js/modules/budgets-v36.js'),'utf8');
const back=fs.readFileSync(path.join(root,'netlify/functions/budgets.js'),'utf8');
const boot=fs.readFileSync(path.join(root,'assets/js/core/04-bootstrap.js'),'utf8');
new Function(front);new Function(back);
assert(front.includes("const MODULE='budgets'"),'frontend deve usar permissão budgets');
assert(front.includes('3–4 propostas'),'interface deve explicitar 3–4 propostas');
assert(front.includes("data-vg-module=\"budgets\"")||boot.includes("data-vg-module=\"budgets\""),'bootstrap deve carregar budgets');
assert(boot.includes("'budgets'"),'budgets deve ser uma view válida');
assert(!front.includes('MutationObserver'),'módulo de Orçamentos não deve usar MutationObserver global');
assert(!front.includes('setInterval('),'módulo de Orçamentos não deve usar polling contínuo');
assert(back.includes("u.modules.includes('budgets')"),'backend deve validar permissão budgets');
assert(back.includes('canHotel(u,r.hotel)'),'backend deve filtrar/validar hotel');
assert(back.includes('qs.length<3||qs.length>4'),'submissão deve exigir 3 ou 4 propostas');
assert(back.includes("if(decision==='Aprovar')"),'aprovação DO deve ter tratamento específico');
assert(back.includes('quoteId'),'aprovação deve selecionar uma proposta');
assert(back.includes("action==='create-intervention'"),'orçamento aprovado deve poder criar intervenção');
assert(back.includes('finalCost'),'deve existir controlo de custo final/desvio');
console.log('✓ Orçamentos v36: permissões, 3–4 propostas, decisão DO, intervenção e performance validadas.');
