const assert=require('assert');
const fs=require('fs');
const path=require('path');
const cp=require('child_process');
const ROOT=path.resolve(__dirname,'..');
const backend=fs.readFileSync(path.join(ROOT,'netlify/functions/dashboard-sessao.js'),'utf8');
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8');
const lazy=fs.readFileSync(path.join(ROOT,'assets/js/core/08-performance-loader-v35_7.js'),'utf8');
cp.execFileSync(process.execPath,['--check',path.join(ROOT,'netlify/functions/dashboard-sessao.js')],{stdio:'pipe'});
assert(html.includes('nav-cityledger')&&html.includes('cityLedgerRoot')&&lazy.includes('city-ledger-v32.js')&&lazy.includes('city-ledger-v32.css'),'City Ledger deve estar integrado via carregamento modular');
assert(html.includes('nav-unitEconomics')&&html.includes('unitEconomicsRoot')&&lazy.includes('unit-economics-v32.js')&&lazy.includes('unit-economics-v32.css'),'Unit Economics deve estar integrado via carregamento modular');
for(const x of ['ops-cityledger-snapshots','ops-cityledger-chunk','ops-cityledger-chunk-save','ops-cityledger-snapshot-save','ops-cityledger-diligences','ops-cityledger-diligence-save'])assert(backend.includes(x),`endpoint ${x} deve existir`);
assert(backend.includes('CITYLEDGER_SNAPSHOT_PREFIX')&&backend.includes('CITYLEDGER_DATA_PREFIX')&&backend.includes('CITYLEDGER_DILIGENCE_PREFIX'),'Blobs de snapshot, dados e diligências devem ser separados');
assert(backend.includes('String(b.snapshotDate||\"\").localeCompare(String(a.snapshotDate||\"\"))||String(b.createdAt||\"\").localeCompare(String(a.createdAt||\"\"))'),'snapshots da mesma data devem privilegiar o carregamento mais recente');
assert(backend.includes('resource.startsWith("ops-cityledger")'),'acesso genérico a Blobs City Ledger deve ser bloqueado');
assert(backend.includes('createdAt:new Date().toISOString()')||backend.includes('createdAt: new Date().toISOString()'),'data/hora da diligência deve ser carimbada no servidor');
assert(backend.includes('createdBy:authUser.user')||backend.includes('createdBy: authUser.user'),'autor da diligência deve ser derivado da sessão no servidor');
assert(backend.includes('CITYLEDGER_SNAPSHOT_PREFIX')&&backend.includes('isRecoverableBusinessKey'),'City Ledger deve integrar Backup & Recuperação');
assert(backend.includes('byBucket:{}')&&backend.includes('byCurrency:{}'),'Diretor não deve receber agregados de outros hotéis nos metadados');
assert(sw.includes('vg-operations-shell-v35-7')&&!sw.includes('/assets/js/modules/city-ledger-v32.js')&&!sw.includes('/assets/js/modules/unit-economics-v32.js'),'módulos V32 pesados devem sair do pre-cache inicial');
console.log('✓ V32 backend: City Ledger server-side, permissões, diligências auditadas, backup e shell PWA');
