const fs=require('fs'),path=require('path');function ok(c,m){if(!c){console.error('FAIL:',m);process.exit(1)}}
const root=path.join(__dirname,'..'),client=fs.readFileSync(path.join(root,'assets/js/modules/complaints-v36.js'),'utf8'),fn=fs.readFileSync(path.join(root,'netlify/functions/complaints.js'),'utf8'),boot=fs.readFileSync(path.join(root,'assets/js/core/04-bootstrap.js'),'utf8');
new Function(client);new Function('require','exports','module','Buffer',fn);
ok(boot.includes('complaints-v36.js'),'bootstrap carrega Reclamações');ok(boot.includes("'complaints'"),'routing reconhece complaints');
ok(client.includes('Reclamações'),'interface tem módulo Reclamações');ok(client.includes('value="complaints"'),'Setup expõe permissão Reclamações');ok(!client.includes('new MutationObserver'),'módulo não usa MutationObserver global');ok(!client.includes('setInterval('),'módulo não usa polling contínuo');
ok(client.includes("'Devolução','Noites gratuitas','Desconto','Refeições','Outra'"),'compensações definidas');ok(client.includes('Registar resposta enviada ao cliente'),'interface exige registo da resposta');ok(client.includes('Registar decisão DO'),'interface expõe decisão DO');
ok(fn.includes("u?.modules)&&u.modules.includes('complaints')"),'backend exige permissão complaints');ok(fn.includes('if(r&&canHotel(u,r.hotel))'),'listagem filtra por hotel no servidor');ok(fn.includes("if(!direction(u))return forbid('A decisão está reservada à Direção de Operações.')"),'decisão reservada ao DO');
ok(fn.includes("const DECISIONS=new Set(['Aprovar','Recusar','Solicitar esclarecimentos'])"),'três decisões DO preservadas');ok(fn.includes("const COMP=new Set(['Sem compensação','Devolução','Noites gratuitas','Desconto','Refeições','Outra'])"),'tipos de compensação preservados');
ok(fn.includes('function hasResponseSent(r)'),'backend deve reconhecer resposta enviada de forma robusta');ok(fn.includes("if(!hasResponseSent(r))return bad('Não é possível arquivar: ainda não existe registo de resposta enviada ao cliente.')"),'arquivo bloqueado sem resposta enviada');ok(fn.includes("if(r.status!=='Concluída')return bad(`Não é possível arquivar:"),'arquivo exige estado Concluída');ok(fn.includes("r.responseSentAt=new Date().toISOString()"),'resposta enviada fica registada');ok(fn.includes("r.status='A aguardar decisão DO'"),'workflow de aprovação DO existe');ok(fn.includes("r.history=(r.history||[]).concat"),'alterações ficam no histórico');ok(fn.includes("store.setJSON(fileKey(r.id,fid)"),'anexos persistem em Netlify Blobs');
console.log('✓ Reclamações: workflow, compensações, permissões por hotel, aprovação DO, resposta e arquivo robusto validados.');