const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const front=fs.readFileSync(path.join(root,'assets/js/modules/energy-multi-pdf-v36.js'),'utf8');
const back=fs.readFileSync(path.join(root,'netlify/functions/energy-files.js'),'utf8');
const boot=fs.readFileSync(path.join(root,'assets/js/core/04-bootstrap.js'),'utf8');
new Function(front);new Function('require','exports','module','Buffer',back);
assert(front.includes('input.multiple=true'),'input de Energia deve aceitar múltiplos PDFs');
assert(front.includes('files.length>10'),'frontend deve limitar a 10 PDFs por fatura');
assert(front.includes('uploadPrimary'),'primeiro PDF deve manter compatibilidade com o registo principal');
assert(front.includes('uploadExtra'),'PDFs adicionais devem ser persistidos separadamente');
assert(front.includes('Documentos da fatura'),'deve existir gestão de documentos da fatura');
assert(back.includes("action==='upload'"),'backend adicional deve aceitar upload');
assert(back.includes("action==='file'"),'backend adicional deve permitir abrir PDF');
assert(back.includes("action==='delete'"),'backend adicional deve permitir remover PDF');
assert(back.includes('current.length>=9'),'backend deve limitar a 9 adicionais, totalizando 10 com o principal');
assert(back.includes('canHotel'),'backend deve preservar restrição por hotel');
assert(boot.includes('energy-multi-pdf-v36.js'),'bootstrap deve carregar suporte multi-PDF');
assert(!front.includes('MutationObserver'),'suporte multi-PDF não deve usar observer global');
assert(!front.includes('setInterval('),'suporte multi-PDF não deve usar polling');
console.log('✓ Energia multi-PDF: até 10 documentos, gestão e segurança por hotel validadas.');