const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const p=n=>path.join(root,n);
const frontPath=p('assets/js/modules/energy-multi-pdf-v36.js');
const delUiPath=p('assets/js/modules/energy-document-delete-ui-v36.js');
const backPath=p('netlify/functions/energy-files.js');
const delBackPath=p('netlify/functions/energy-document-delete.js');
const bootPath=p('assets/js/core/04-bootstrap.js');
[frontPath,delUiPath,backPath,delBackPath,bootPath].forEach(f=>assert(fs.existsSync(f),`Ficheiro em falta: ${path.relative(root,f)}`));
const front=fs.readFileSync(frontPath,'utf8');
const delUi=fs.readFileSync(delUiPath,'utf8');
const back=fs.readFileSync(backPath,'utf8');
const delBack=fs.readFileSync(delBackPath,'utf8');
const boot=fs.readFileSync(bootPath,'utf8');
new Function(front);
new Function(delUi);
new Function('require','exports','module','Buffer',back);
new Function('require','exports','module','Buffer',delBack);
assert(/multiple\s*=\s*true/.test(front),'input de Energia deve aceitar múltiplos PDFs');
assert(front.includes('uploadPrimary')&&front.includes('uploadExtra'),'deve suportar PDF principal e adicionais');
assert(front.includes('Documentos da fatura'),'deve existir gestão de documentos da fatura');
assert(delUi.includes('energy-document-delete'),'interface deve usar o serviço de eliminação auditada');
assert(delUi.includes("kind:'primary'")||delUi.includes('kind:"primary"'),'interface deve permitir remover o PDF principal');
assert(delUi.includes("kind:'extra'")||delUi.includes('kind:"extra"'),'interface deve permitir remover PDFs adicionais');
assert(delBack.includes("'primary','extra'")||delBack.includes('"primary","extra"'),'backend deve aceitar documentos principal e adicional');
assert(delBack.includes('Removeu PDF da fatura'),'eliminação deve ficar registada no histórico');
assert(delBack.includes('canHotel'),'eliminação deve respeitar o hotel autorizado');
assert(boot.includes('energy-multi-pdf-v36.js'),'bootstrap deve carregar suporte multi-PDF');
assert(boot.includes('energy-document-delete-ui-v36.js'),'bootstrap deve carregar a interface de eliminação');
assert(!front.includes('MutationObserver')&&!delUi.includes('MutationObserver'),'gestão documental não deve usar observer global');
assert(!front.includes('setInterval(')&&!delUi.includes('setInterval('),'gestão documental não deve usar polling');
console.log('✓ Energia: múltiplos PDFs, abertura, eliminação auditada e segurança por hotel validadas.');
