const assert=require('assert');
const fs=require('fs');
const path=require('path');
const cp=require('child_process');
const ROOT=path.resolve(__dirname,'..');
const fixPath=path.join(ROOT,'assets/js/core/fb-ratios-period-fix-v36.js');
const bootPath=path.join(ROOT,'assets/js/core/04-bootstrap.js');
const corePath=path.join(ROOT,'assets/js/core/02-navigation-kpis.js');
assert(fs.existsSync(fixPath),'correção de rácios V36 em falta');
const chk=cp.spawnSync(process.execPath,['--check',fixPath],{encoding:'utf8'});assert.strictEqual(chk.status,0,chk.stderr);
const F=fs.readFileSync(fixPath,'utf8'),B=fs.readFileSync(bootPath,'utf8'),C=fs.readFileSync(corePath,'utf8');
assert(B.includes('fb-ratios-period-fix-v36.js'),'bootstrap deve carregar correção dos rácios');
assert(F.includes("hotels_rev?.[hotel]?.ALIMENTACAO?.[year]")&&F.includes("['Receita FB']"),'denominador deve vir da receita F&B do P&L selecionado');
assert(F.includes("total*share"),'Receita Detalhada deve servir apenas para repartir o total F&B');
assert(!F.includes("abDetailRevenue(hotel, year, 'AB')"),'correção não pode usar receita detalhada absoluta como denominador A&B');
assert(F.includes('window.ratioAB')&&F.includes('(c1+c2)/r*100'),'A&B deve ser soma custos / receita F&B do mesmo período');
assert(C.includes('const detail = (!useSingleMonth && data === RAW) ? abDetailRevenue'),'teste documenta a regressão antiga que a camada V36 substitui');
console.log('✓ rácios A&B V36: custos e denominadores usam o mesmo período; detalhe apenas reparte a receita');
