const fs=require('fs'),path=require('path');
function ok(c,m){if(!c){console.error('FAIL:',m);process.exit(1)}}
const root=path.join(__dirname,'..');
const client=fs.readFileSync(path.join(root,'assets/js/modules/hr-balances-v36.js'),'utf8');
const fn=fs.readFileSync(path.join(root,'netlify/functions/hr-balances.js'),'utf8');
const boot=fs.readFileSync(path.join(root,'assets/js/core/04-bootstrap.js'),'utf8');
new Function(client);
new Function('require','exports','module','Buffer',fn);
ok(boot.includes('hr-balances-v36.js'),'bootstrap carrega módulo RH');
ok(!boot.includes('hr-balances-access-v36.js'),'bootstrap já não carrega bridge RH concorrente');
ok(!boot.includes('hr-balances-layout-fix-v36.js'),'bootstrap já não carrega layout fix RH');
ok(!boot.includes('hr-balances-import-fix-v36.js'),'bootstrap já não carrega import fix RH');
ok(boot.includes("'hrbalances'"),'routing reconhece hrbalances');
ok(client.includes('Banco de Horas & Férias'),'interface tem título');
ok(client.includes('RH - Saldos por Gozar'),'fonte RH identificada');
ok(client.includes('ensureXLSX'),'importador usa biblioteca Excel');
ok(client.includes('parseSheet'),'existe parser do relatório');
ok(client.includes("'Banco de Horas','Férias','Férias - Anos Anteriores'"),'tipos principais preservados');
ok(client.includes("a>=30?'bad':a>=16?'warn'"),'limites de alerta em horas preservados');
ok(client.includes("a>=10?'bad':a>=5?'warn'"),'limites de alerta em dias preservados');
ok(client.includes('const MODULE=\'hrbalances\',API=\'/.netlify/functions/hr-balances\',PAGE_SIZE=100'),'renderização tem paginação limitada');
ok(client.includes('data-detail="${pi}"'),'detalhe é criado sob pedido');
ok(client.includes('if(opening&&!cell.dataset.loaded)'),'detalhe não é pré-renderizado para todos');
ok(!client.includes('new MutationObserver'),'módulo RH não instala MutationObserver global');
ok(!client.includes('setInterval('),'módulo RH não usa polling contínuo');
ok(client.includes('input type="checkbox" class="vgModuleAccess" value="hrbalances"'),'Setup expõe permissão RH no módulo consolidado');
ok(client.includes('performance.now()'),'módulo mede tempos de fetch/processamento/render');
ok(fn.includes("u?.modules)&&u.modules.includes('hrbalances')"),'backend exige permissão do módulo');
ok(fn.includes('.filter(r=>canHotel(u,r.hotel))'),'backend filtra saldos por hotel antes de responder');
ok(fn.includes("if(!direction(u))return forbid('A atualização dos saldos RH está reservada à Direção de Operações.')"),'só Direção importa saldos');
ok(fn.includes("store.setJSON(SNAP_PREFIX+Date.now(),old)"),'importação cria snapshot anterior');
ok(fn.includes("store.setJSON(DATA_KEY,data)"),'dados persistem em Netlify Blobs');
ok(fn.includes('scopedMeta'),'metadados também respeitam âmbito');
console.log('✓ Banco de Horas & Férias: arquitetura consolidada, performance, importação, persistência e permissões validadas.');
