const fs=require('fs'),path=require('path'),assert=require('assert');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const model=read('src/modern/purchases/theoretical-model.ts');
const controller=read('src/modern/purchases/theoretical-controller.ts');
const renderer=read('src/modern/purchases/theoretical-renderer.ts');
const purchases=read('src/modern/modules/purchases.ts');
const build=read('scripts/build-modern-preview.js');
assert(model.includes('buildTheoryViewModel'),'modelo teórico tipado deve existir');
assert(model.includes("const accepts=(row:{hotel?:unknown})=>selected==='__all'||canonical(row.hotel)===selected"),'modelo deve filtrar por hotel canónico');
assert(model.includes('recipe?.ingredients'),'ingredientes devem ser recalculados pelas fichas das vendas filtradas');
assert(controller.includes('TheoreticalConsumptionState'),'controller deve gerir estado próprio');
assert(controller.includes("hub.dataset.tab!=='theoretical'"),'controller só deve atuar no separador teórico');
assert(renderer.includes('data-modern-theory-hotel'),'renderer deve expor filtro de hotel moderno');
assert(renderer.includes('Venda\\s*→\\s*ficha técnica'),'renderer deve preservar a análise venda para ficha');
assert(!controller.includes('MutationObserver')&&!renderer.includes('MutationObserver'),'consumo teórico moderno não deve depender de MutationObserver');
assert(purchases.includes("import { TheoreticalConsumptionController }"),'módulo purchases deve integrar o controller teórico');
assert(purchases.includes("[data-abtab=\"theoretical\"]"),'módulo purchases deve reagir ao separador teórico');
assert(!build.includes('theoretical-consumption-fix-v40.js'),'preview não deve injetar o patch teórico legado');
console.log('✓ Modern theoretical consumption: model/state/controller/renderer sem MutationObserver');
