const fs=require('fs'),path=require('path'),assert=require('assert');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const model=read('src/modern/data/financials-model.ts');
const service=read('src/modern/data/financials-service.ts');
const bridge=read('src/modern/data/financials-bridge.ts');
const legacy=read('src/modern/data/legacy-data-sources.ts');
const costs=read('src/modern/data/costs-service.ts');
const usali=read('assets/js/modules/pl-usali-reconciliation-v46.js');
const main=read('src/modern/main.ts');
assert(model.includes('interface FinancialsSourceSnapshot'),'deve existir contrato financeiro tipado');
assert(model.includes('raw:unknown'),'snapshot financeiro deve preservar payload legado durante a migração');
assert(model.includes('canonicalFinancialValue'),'deve existir acesso canónico a métricas financeiras por hotel/ano');
assert(model.includes("canonicalFinancialTotal(value,hotels,'Receita Total',year)"),'Receita Total oficial deve ter um único accessor moderno');
assert(model.includes('reconcileUsaliRevenue'),'modelo financeiro deve expor reconciliação USALI testável');
assert(service.includes("ensureDataSource<FinancialsSourceSnapshot>('financials'"),'serviço financeiro deve ser a fachada do registry');
assert(costs.includes('financialsData(force)'),'custos deve passar pela fachada financeira');
assert(costs.includes('costsSnapshot(financials.raw)'),'normalização de custos deve receber apenas o payload financeiro');
assert(bridge.includes('modernFinancials'),'deve existir bridge financeiro moderno para compatibilidade legacy');
assert(bridge.includes("sum('hotels_ops','Receita Total'"),'bridge deve expor Receita Total oficial');
assert(usali.includes("modernSum('hotels_rev'"),'USALI deve preferir a fonte financeira moderna para receitas');
assert(usali.includes("modernSum('hotels_costs'"),'USALI deve preferir a fonte financeira moderna para custos');
assert(usali.includes("modernSum('hotels_ops'"),'USALI deve preferir a fonte financeira moderna para indicadores');
assert(main.includes('installFinancialsBridge();'),'bootstrap moderno deve instalar bridge financeiro antes do USALI');
assert(legacy.includes("case'financials':return financialsSnapshot(w.RAW)"),'registry deve adaptar RAW para snapshot financeiro tipado');
console.log('✓ Modern financials source: fachada, bridge e USALI usam o domínio financeiro moderno');
