const fs=require('fs'),path=require('path'),assert=require('assert');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const registry=read('src/modern/core/module-registry.ts');
const catalog=read('src/modern/core/view-catalog.ts');
const main=read('src/modern/main.ts');
const mod=read('src/modern/modules/financial-revenue.ts');
const renderer=read('src/modern/revenue/financial-revenue-renderer.ts');
const kpis=read('src/modern/revenue/financial-kpi-renderer.ts');
const legacy=read('assets/js/core/02-navigation-kpis.js');
assert(registry.includes("| 'financial-revenue'"),'registry deve incluir módulo financeiro de Receitas');
assert(catalog.includes("id:'receitas'")&&catalog.includes("moduleId:'financial-revenue'"),'Receitas deve usar lifecycle moderno');
assert(main.includes("registerModule('financial-revenue'"),'main deve registar Receitas em lazy loading');
assert(mod.includes("financialsData(force)"),'Receitas deve preparar a fonte financeira tipada');
assert(mod.includes("renderFinancialKpis(financials,'kpiGrid')"),'Receitas deve renderizar KPIs a partir do snapshot financeiro moderno');
assert(!mod.includes('buildKPIs'),'módulo moderno já não deve depender do agregador KPI legacy');
assert(mod.includes('renderFinancialRevenue(financials)'),'módulo deve usar renderer moderno de Receitas');
assert(!mod.includes('window.buildChartsReceitas?.()'),'módulo já não deve depender do renderer legacy de gráficos');
assert(!mod.includes('window.buildRevTable?.()'),'módulo já não deve depender do renderer legacy da tabela');
assert(!mod.includes('refreshAll'),'módulo moderno de Receitas não pode disparar refreshAll');
assert(renderer.includes("dc('chartRevAloj'")&&renderer.includes("dc('chartRevFB'")&&renderer.includes("dc('chartVarPct'"),'renderer moderno deve preservar os três gráficos existentes');
assert(renderer.includes("document.getElementById('revTableBody')"),'renderer moderno deve preservar a tabela existente');
assert(kpis.includes("document.getElementById(targetId)"),'renderer KPI deve escrever apenas no alvo recebido');
assert(kpis.includes("'Receita Total'" )&&kpis.includes("'GOP COM SEDE'"),'KPIs modernos devem usar métricas financeiras canónicas');
assert(kpis.includes("'Custos Totais ${current}'")||kpis.includes('Custos Totais'),'KPIs modernos devem manter custos totais');
assert(!kpis.includes('RAW.'),'renderer KPI moderno não deve ler RAW global diretamente');
assert(legacy.includes('function buildChartsReceitas()')&&legacy.includes('function buildRevTable()'),'renderers legacy continuam disponíveis apenas como compatibilidade durante a migração');
console.log('✓ Modern Receitas: lifecycle, KPIs e renderer financeiro moderno preservam a apresentação atual');
