const assert=require('assert');
const fs=require('fs');
const path=require('path');
const cp=require('child_process');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');

const html=read('index.html');
const bridge=read('assets/js/modules/occupancy-modern-bridge-v40.js');
const source=read('src/modern/data/legacy-data-sources.ts');
const model=read('src/modern/data/occupancy-model.ts');
const service=read('src/modern/data/occupancy-service.ts');
const state=read('src/modern/occupancy/occupancy-state.ts');
const controller=read('src/modern/occupancy/occupancy-controller.ts');
const renderer=read('src/modern/occupancy/occupancy-renderer.ts');
const moduleCode=read('src/modern/modules/occupancy.ts');
const mountCode=(moduleCode.match(/async\s+mount\s*\(root\)\s*\{([\s\S]*?)\n\s*\},\s*\n\s*unmount/)||[])[1]||'';

assert(!html.includes('occupancy-modern-bridge-v40.js'),'bridge de Ocupação moderna deve permanecer desligado do index.html');
assert(!bridge.includes('fetch('),'bridge de Ocupação não pode criar tráfego de rede');
assert(/typeof\s+OCC_SNAPSHOTS\s*===\s*['"]undefined['"]/.test(bridge)&&bridge.includes('occupancyModernBridge'),'bridge deve ler snapshots legados sem alterar ocupacao.js');
assert(bridge.includes('applySelection')&&/setSelectValue\s*\(\s*['"]occHotelSel['"]/.test(bridge)&&/setSelectValue\s*\(\s*['"]occSnapSel['"]/.test(bridge),'bridge deve sincronizar hotel/snapshot sem controlar navegação');
assert(/case\s*['"]occupancy['"]\s*:/.test(source)&&/return\s+occupancySnapshot\s*\(\s*w\s*\)\s*;?/.test(source),'fonte occupancy deve usar contrato específico e não RAW');
assert(model.includes('occupancyPickup')&&model.includes('averageOccupancy'),'modelo deve calcular médias/pickup fora do módulo legado');
assert(/ensureDataSource\s*<\s*OccupancySourceSnapshot\s*>\s*\(\s*['"]occupancy['"]/.test(service)&&service.includes('occupancyDiagnostics'),'serviço deve consumir cache seletiva e expor diagnóstico');
assert(state.includes('class OccupancyStateStore')&&/subscribe\s*\(/.test(state),'estado de seleção deve estar desacoplado do DOM');
assert(/hasOwnProperty\.call\s*\(\s*next\s*,\s*['"]year['"]\s*\)/.test(state)&&/hasOwnProperty\.call\s*\(\s*next\s*,\s*['"]month['"]\s*\)/.test(state),'estado moderno deve permitir limpar explicitamente filtros de ano e mês');
assert(state.includes('class OccupancyStateStore')&&controller.includes('class OccupancyController')&&controller.includes('syncFromLegacy')&&/refresh\s*\(\s*\)/.test(controller),'controlador deve coordenar estado/dados sem navegar');
assert(renderer.includes('renderOccupancyReadOnly')&&!/getElementById\s*\(\s*['"]occHotelSel['"]/.test(renderer)&&!/getElementById\s*\(\s*['"]occSnapSel['"]/.test(renderer),'renderer deve expor renderização própria sem depender dos controlos DOM legados');
assert(/host\.dataset\.modernOccupancyReadonly\s*=\s*['"]true['"]/.test(renderer)&&/table\.dataset\.modernOccupancyTable\s*=\s*['"]true['"]/.test(renderer),'renderer deve criar uma vista moderna identificável e tabela própria');
assert(/controls\.dataset\.modernOccupancyControls\s*=\s*['"]true['"]/.test(renderer)&&/selectControl\s*\(\s*['"]Hotel['"]/.test(renderer)&&/selectControl\s*\(\s*['"]Snapshot['"]/.test(renderer)&&/selectControl\s*\(\s*['"]Ano['"]/.test(renderer)&&/selectControl\s*\(\s*['"]Mês['"]/.test(renderer),'renderer moderno deve oferecer filtros próprios de hotel, snapshot, ano e mês');
assert(/actions\.onSelectionChange\?\.\(\s*\{\s*hotel\s*:\s*hotelSelect\.value\s*\}\s*\)/.test(renderer)&&/actions\.onRefresh\?\.\(\s*\)/.test(renderer),'filtros e atualização devem comunicar por callbacks tipados e não por DOM legado');
assert(/selection\.month\s*==\s*null\s*\?\s*MONTHS/.test(renderer)&&renderer.includes('shownValues'),'filtro mensal deve limitar a visualização sem alterar os dados de origem');
assert(!moduleCode.includes('legacyView(')&&!moduleCode.includes('setView(')&&!moduleCode.includes('refreshAll'),'módulo moderno de Ocupação não pode reintroduzir navegação/refresh global');
assert(/occupancyController\.prepare\s*\(\s*\)/.test(moduleCode)&&moduleCode.includes('occupancyState.subscribe')&&/renderCurrent\s*\(\s*\)/.test(moduleCode),'módulo deve preparar a fonte, reagir ao estado moderno e renderizar sem depender da vista legada');
assert(/occupancyController\.setSelection\s*\(\s*next\s*\)/.test(moduleCode)&&/occupancyController\.refresh\s*\(\s*\)/.test(moduleCode),'interações modernas devem passar pelo controlador');
assert(mountCode&&!/bridge\s*\(\s*\)\?\.refresh\?\.\(\s*\)/.test(mountCode),'mount moderno não deve pedir renderização à vista legada');
cp.execFileSync(process.execPath,['--check',path.join(ROOT,'assets/js/modules/occupancy-modern-bridge-v40.js')],{stdio:'pipe'});
console.log('✓ modern occupancy: filtros, estado, controlador, renderização e atualização seletiva validados');
