const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const refundsFront=fs.readFileSync(path.join(root,'assets/js/modules/refunds-v36.js'),'utf8');
const refundsBack=fs.readFileSync(path.join(root,'netlify/functions/refunds.js'),'utf8');
const unbilledFront=fs.readFileSync(path.join(root,'assets/js/modules/unbilled-v36.js'),'utf8');
const unbilledBack=fs.readFileSync(path.join(root,'netlify/functions/unbilled.js'),'utf8');
const catalog=fs.readFileSync(path.join(root,'assets/js/auth/operations-modules-catalog-v36.js'),'utf8');
const boot=fs.readFileSync(path.join(root,'assets/js/core/04-bootstrap.js'),'utf8');
new Function(refundsFront);new Function('require','exports','module','Buffer',refundsBack);new Function(unbilledFront);new Function('require','exports','module','Buffer',unbilledBack);new Function(catalog);new Function(boot);
assert(refundsFront.includes('nav-refunds')&&refundsFront.includes('Devoluções'),'Devoluções deve criar navegação');
assert(refundsBack.includes("includes('refunds')")&&refundsBack.includes('canHotel'),'Devoluções deve respeitar módulo e hotel');
assert(unbilledFront.includes('nav-unbilled')&&unbilledFront.includes('Contas por Faturar'),'Contas por Faturar deve criar navegação');
assert(unbilledFront.includes("'0–30'")&&unbilledFront.includes("'31–60'")&&unbilledFront.includes("'61–90'")&&unbilledFront.includes("'+90'"),'Aging deve ter quatro escalões');
assert(unbilledBack.includes("action==='comment'")&&unbilledBack.includes('Diligência'),'Backend deve guardar diligências');
assert(unbilledBack.includes("action==='batch'")&&unbilledFront.includes('Importar Excel/CSV'),'Deve suportar importação em lote');
assert(catalog.includes("['refunds','Devoluções'")&&catalog.includes("['unbilled','Contas por Faturar'"),'Setup deve expor ambas as permissões');
assert(boot.includes('refunds-v36.js')&&boot.includes('unbilled-v36.js'),'Bootstrap deve carregar ambos os módulos');
assert(boot.includes("'refunds','unbilled'"),'Ambas as vistas devem ser navegáveis por hash');
assert(!refundsFront.includes('MutationObserver')&&!unbilledFront.includes('MutationObserver'),'Módulos não devem usar observers globais');
assert(!refundsFront.includes('setInterval(')&&!unbilledFront.includes('setInterval('),'Módulos não devem usar polling');
console.log('✓ Devoluções e Contas por Faturar: navegação, permissões, aging, diligências e segurança validadas.');