const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const front=fs.readFileSync(path.join(root,'assets/js/modules/refunds-v36.js'),'utf8');
const back=fs.readFileSync(path.join(root,'netlify/functions/refunds.js'),'utf8');
const boot=fs.readFileSync(path.join(root,'assets/js/core/04-bootstrap.js'),'utf8');
new Function(front);new Function('require','exports','module','Buffer',back);
assert(front.includes("MODULE='refunds'"),'frontend deve usar permissão refunds');
assert(front.includes('vgRefundsCreateFromComplaint'),'deve permitir criar devolução a partir de reclamação');
assert(front.includes('A aguardar DAF'),'frontend deve contemplar passagem pela DAF');
assert(back.includes("action==='submit'"),'backend deve suportar submissão à DO');
assert(back.includes("action==='decide'"),'backend deve suportar decisão DO');
assert(back.includes("action==='markDaf'"),'backend deve suportar encaminhamento DAF');
assert(back.includes("action==='processed'"),'backend deve suportar processamento');
assert(back.includes("action==='complete'"),'backend deve suportar conclusão');
assert(back.includes("action==='archive'"),'backend deve suportar arquivo');
assert(back.includes('canHotel'),'backend deve restringir por hotel');
assert(back.includes('direction(u)'),'aprovação deve distinguir Direção de Operações');
assert(back.includes('history'),'processo deve manter histórico');
assert(boot.includes('refunds-v36.js'),'bootstrap deve carregar Devoluções');
assert(boot.includes("'refunds'"),'refunds deve ser uma vista válida');
assert(!front.includes('MutationObserver'),'módulo não deve usar observer global');
assert(!front.includes('setInterval('),'módulo não deve usar polling');
console.log('✓ Devoluções: workflow DO/DAF, âmbito por hotel, ligação a reclamação e histórico validados.');