const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(ROOT,f),'utf8');
const persistence=read('assets/js/core/03-persistence-sharing.js');
const reputation=read('assets/js/modules/reputacao.js');
const base=read('assets/css/base.css');
assert(persistence.includes('var REP_STORE = window.REP_STORE || (window.REP_STORE = {});'),'REP_STORE tem de existir no shell antes da reputação lazy');
assert(persistence.includes('var rtSelected = window.rtSelected instanceof Set'),'rtSelected tem de existir no shell antes da reputação lazy');
assert(reputation.includes('var REP_STORE = window.REP_STORE || (window.REP_STORE = {});'),'Reputação lazy deve reutilizar REP_STORE canónico');
assert(!reputation.includes('const REP_STORE = {};'),'Reputação não pode redeclarar REP_STORE de forma incompatível');
assert(base.includes('.vg-agenda-modal { display:none; }'),'Modal estático da Agenda deve ficar escondido antes do CSS lazy');
console.log('✓ V35.7 hotfix: stores de reputação no shell e modal Agenda protegido');
