import { currentApprovalsData, type ApprovalDecision } from '../data/approvals-service';
import type { ApprovalRecord } from '../data/approvals-model';
import type { ApprovalsSelection } from './approvals-state';
export interface ApprovalActions{onSelectionChange?:(n:Partial<ApprovalsSelection>)=>void;onRefresh?:()=>void|Promise<void>;onMessage?:(r:ApprovalRecord,text:string)=>void|Promise<void>;onSubmit?:(r:ApprovalRecord,comment:string)=>void|Promise<void>;onDecision?:(r:ApprovalRecord,d:ApprovalDecision,comment:string)=>void|Promise<void>;onState?:(r:ApprovalRecord,status:string,comment:string)=>void|Promise<void>;onArchive?:(r:ApprovalRecord)=>void|Promise<void>;}
const STATES:Record<string,string[]>={complaint:['Em preparação','A aguardar DO','Esclarecimentos solicitados','Aprovada','Recusada','Resposta ao cliente','Concluída'],refund:['Em preparação','A aguardar DO','Esclarecimentos solicitados','A aguardar DAF','Recusada','Processada','Concluída'],budget:['Em preparação','A aguardar DO','Esclarecimentos solicitados','Aprovado','Recusado','Adjudicado','Em execução','Concluído']};
type AuthWindow=Window&{vgAuthCurrent?:()=>{role?:string}|null;showToast?:(m:string,e?:boolean)=>void};
function isDO(){const role=String((window as AuthWindow).vgAuthCurrent?.()?.role||'').toLowerCase();return role==='direcao'||role==='admin';}
function toast(m:string,e=false){(window as AuthWindow).showToast?.(m,e);}
function control(label:string,value:string,values:string[]){const l=document.createElement('label');const s=document.createElement('span');s.textContent=label;const el=document.createElement('select');[{v:'__all__',t:'Todos'},...values.map(v=>({v,t:v}))].forEach(o=>{const x=document.createElement('option');x.value=o.v;x.textContent=o.t;el.appendChild(x)});el.value=value;l.append(s,el);return l;}
function btn(text:string,run:()=>void|Promise<void>,danger=false){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=danger?'btn danger':'btn';b.onclick=async()=>{b.disabled=true;try{await run();}catch(e){toast(e instanceof Error?e.message:String(e),true);}finally{b.disabled=false;}};return b;}
function actionsCell(r:ApprovalRecord,a:ApprovalActions){const td=document.createElement('td');const wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:4px;flex-wrap:wrap';if(r.archived){td.textContent='Arquivado';return td;}wrap.append(btn('Mensagem',async()=>{const text=prompt('Mensagem / esclarecimento:')?.trim();if(text)await a.onMessage?.(r,text);}));if(['Em preparação','Esclarecimentos solicitados'].includes(r.status))wrap.append(btn('Submeter à DO',async()=>{const c=prompt('Comentário para a submissão:')||'';await a.onSubmit?.(r,c);}));if(isDO()&&r.status==='A aguardar DO'){wrap.append(btn('Aprovar',async()=>{const c=prompt('Comentário obrigatório da decisão:')?.trim();if(c)await a.onDecision?.(r,'approve',c);}),btn('Esclarecimentos',async()=>{const c=prompt('Indique o esclarecimento necessário:')?.trim();if(c)await a.onDecision?.(r,'clarify',c);}),btn('Recusar',async()=>{const c=prompt('Comentário obrigatório da recusa:')?.trim();if(c)await a.onDecision?.(r,'reject',c);},true));}
const terminal=r.type==='budget'?'Concluído':'Concluída';if(r.status===terminal)wrap.append(btn('Arquivar',async()=>{if(confirm(`Arquivar ${r.code}?`))await a.onArchive?.(r);},true));else{const next=(STATES[r.type]||[]).filter(x=>x!==r.status);if(next.length)wrap.append(btn('Alterar estado',async()=>{const status=prompt(`Novo estado:\n${next.join('\n')}`)?.trim();if(!status||!next.includes(status))return toast('Estado inválido.',true);const c=prompt('Comentário obrigatório:')?.trim();if(c)await a.onState?.(r,status,c);}));}td.appendChild(wrap);return td;}
export function renderApprovals(root:HTMLElement,sel:Readonly<ApprovalsSelection>,actions:ApprovalActions={}){let host=root.querySelector<HTMLElement>('[data-modern-approvals]');if(!host){host=document.createElement('section');host.dataset.modernApprovals='true';root.appendChild(host);}const data=currentApprovalsData();const title=document.createElement('h2');title.textContent='Aprovações';if(!data.available){const p=document.createElement('p');p.textContent='Sem dados de Aprovações disponíveis.';host.replaceChildren(title,p);return host;}
const hotels=[...new Set(data.records.map(r=>r.hotel))].sort((a,b)=>a.localeCompare(b,'pt'));const types=[...new Set(data.records.map(r=>r.type))].sort((a,b)=>a.localeCompare(b,'pt'));const statuses=[...new Set(data.records.map(r=>r.status))].sort((a,b)=>a.localeCompare(b,'pt'));const h=control('Hotel',sel.hotel,hotels),t=control('Tipo',sel.type,types),s=control('Estado',sel.status,statuses);h.querySelector('select')!.onchange=e=>actions.onSelectionChange?.({hotel:(e.target as HTMLSelectElement).value});t.querySelector('select')!.onchange=e=>actions.onSelectionChange?.({type:(e.target as HTMLSelectElement).value});s.querySelector('select')!.onchange=e=>actions.onSelectionChange?.({status:(e.target as HTMLSelectElement).value});const refresh=btn('Atualizar',()=>actions.onRefresh?.());const controls=document.createElement('div');controls.dataset.modernApprovalsControls='true';controls.append(h,t,s,refresh);const rows=data.records.filter(r=>(sel.hotel==='__all__'||r.hotel===sel.hotel)&&(sel.type==='__all__'||r.type===sel.type)&&(sel.status==='__all__'||r.status===sel.status));const summary=document.createElement('p');summary.textContent=`${rows.length} processos`;const table=document.createElement('table');table.dataset.modernApprovalsTable='true';const head=document.createElement('thead');const trh=document.createElement('tr');['N.º','Hotel','Tipo','Assunto','Estado','Autor','Data','Valor','Ações'].forEach(v=>{const th=document.createElement('th');th.textContent=v;trh.appendChild(th)});head.appendChild(trh);table.appendChild(head);const body=document.createElement('tbody');rows.slice(0,1000).forEach(r=>{const tr=document.createElement('tr');[r.code,r.hotel,r.typeLabel,r.title,r.status,r.author,r.createdAt,r.amount==null?'—':new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(r.amount)].forEach(v=>{const td=document.createElement('td');td.textContent=String(v);tr.appendChild(td)});tr.appendChild(actionsCell(r,actions));body.appendChild(tr)});table.appendChild(body);host.replaceChildren(title,controls,summary,table);return host;}
export function clearApprovals(root:HTMLElement){root.querySelector('[data-modern-approvals]')?.remove();}
